# coding: utf-8

# flake8: noqa

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccessAndDataPolicyApi",
    "ApplicationGroupsApi",
    "ApplicationsApi",
    "ConfigurationManagementApi",
    "CustomizationPolicyApi",
    "DeviceGroupsApi",
    "DevicesApi",
    "PluginsApi",
    "SecurityPolicyApi",
    "SignInPolicyApi",
    "UserGroupsApi",
    "UserRequestsApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccessAndDataRuleDetailed",
    "AccessAndDataRuleDetailedMetadata",
    "AccessAndDataRuleMode",
    "AddRemoveApps",
    "AddRemoveCidrs",
    "AddRemoveUrls",
    "AllowBlockControl",
    "AllowBlockControlAction",
    "AllowedOrBlockedExtensionEntry",
    "AllowedOrBlockedExtensionsControl",
    "AllowedOrBlockedExtensionsControlMode",
    "AllowedOrBlockedExtensionsControlRiskLevel",
    "AllowedPrintersControl",
    "AllowedPrintersControlAction",
    "ApiError",
    "ApiErrorError",
    "ApiErrorErrorCode",
    "ApiErrorErrorDetailsInner",
    "ApplicationGroup",
    "ApplicationGroupApplicationsInner",
    "ApplicationGroupApplicationsInnerType",
    "ApplicationItem",
    "ApplicationTypeInput",
    "AttributeObject",
    "AttributeObjectBrowserBrand",
    "AttributeObjectBrowserEol",
    "AttributeObjectClientCertificate",
    "AttributeObjectCsZtaScore",
    "AttributeObjectCsZtaScoreBreakdownScores",
    "AttributeObjectDeviceManagement",
    "AttributeObjectDeviceManufacturer",
    "AttributeObjectDeviceType",
    "AttributeObjectDiskEncryption",
    "AttributeObjectEndpointProtection",
    "AttributeObjectFileExistence",
    "AttributeObjectFirewall",
    "AttributeObjectLocationServices",
    "AttributeObjectMobileDeviceManagement",
    "AttributeObjectMobileDeviceManufacturers",
    "AttributeObjectMobileDeviceType",
    "AttributeObjectMobileOsVersion",
    "AttributeObjectMobileRootJailBreakStatus",
    "AttributeObjectMobileScreenLock",
    "AttributeObjectNormalOSBootMode",
    "AttributeObjectOsPassword",
    "AttributeObjectOsVersion",
    "AttributeObjectPrivilegedProcess",
    "AttributeObjectRegistry",
    "AttributeObjectRemoteConnection",
    "AttributeObjectRunningProcesses",
    "AttributeObjectScreenLock",
    "AttributeObjectSerialNumber",
    "AttributeObjectSystemIntegrity",
    "AuthenticationFactorControl",
    "AuthenticationFactorIdentityProviderControl",
    "AuthenticationFactorIdentityProviderControlIdentityProvider",
    "AuthenticationFactorIdentityProviderControlIdentityProviderProfileSource",
    "AuthenticationFactorIdentityProviderControlMethod",
    "AuthenticationFactorPasskeyControl",
    "AuthenticationFactorPasskeyControlMethod",
    "AuthenticationFactorPasskeyControlPasskey",
    "AuthenticationFactorPinCodeControl",
    "AuthenticationFactorPinCodeControlMethod",
    "AuthenticationFactorPinCodeControlPinCode",
    "AuthenticationFactorPinCodeControlPinCodeMaxFailedAttempts",
    "AuthenticationServerAllowlistControl",
    "AuthenticationServerAllowlistControlAction",
    "BaseApplication",
    "BaseApplicationInput",
    "BaseApplicationWithUrls",
    "BasePatchApplicationInput",
    "BasePatchRuleRequest",
    "BasePolicyItem",
    "BasePostRuleRequest",
    "BlockExtensionsByPermissionsControl",
    "BlockExtensionsByPermissionsControlAction",
    "BlockExtensionsByPermissionsControlBlockedPermissionsInner",
    "BrowserBrand",
    "BrowserBrandDetails",
    "BrowserHistoryControl",
    "BrowserHistoryControlAction",
    "BrowserLockControl",
    "BrowserLockControlAction",
    "BrowserLockControlIdleTimeoutMinutes",
    "BrowserSelfProtectionControl",
    "BrowserSelfProtectionControlAction",
    "BrowserSelfProtectionControlEnforcement",
    "BrowserSelfProtectionModule",
    "BrowserSelfProtectionModuleWindows",
    "BrowserSelfProtectionWindowsDriverStatus",
    "BulkCreatedItem",
    "BulkDeleteApplicationsRequest",
    "CatalogApplication",
    "CatalogApplicationAllOfType",
    "CatalogAttributes",
    "CertificateDN",
    "ConcurrentNumberOfDevicesControl",
    "ConcurrentNumberOfDevicesControlAction",
    "ConcurrentNumberOfDevicesControlLimitMode",
    "CookiesControl",
    "CookiesControlAction",
    "CreateAccessAndDataRuleRequest",
    "CreateApplication201Response",
    "CreateApplicationPlugin201Response",
    "CreateCustomizationRuleRequest",
    "CreateDeviceGroup201Response",
    "CreateOrReplaceAppGroupInput",
    "CreateOrReplaceAppInput",
    "CreateSecurityRule201Response",
    "CreateSecurityRuleRequest",
    "CreateSignInRuleRequest",
    "CreateUserGroup201Response",
    "CreateUserGroupRequest",
    "CrowdstrikeZTAPosture",
    "CsZtaBasicScoreLevel",
    "CsZtaScore",
    "CustomApplication",
    "CustomApplicationAllOfType",
    "CustomApplicationInput",
    "CustomPatchApplicationInput",
    "CustomTypeInput",
    "CustomizationRuleDetailed",
    "DefinitionUpdateTimeframe",
    "DeleteApplicationPlugin200Response",
    "DeleteUserGroup200Response",
    "Device",
    "DeviceArchiveResponse",
    "DeviceBrowserBrand",
    "DeviceDeleteResponse",
    "DeviceDeviceType",
    "DeviceDiskEncryptionDetails",
    "DeviceDiskEncryptionStatus",
    "DeviceEPP",
    "DeviceFirewallDetails",
    "DeviceFirewallStatus",
    "DeviceForceReauthResponse",
    "DeviceGroup",
    "DeviceGroupPatchRequest",
    "DeviceGroupPlatform",
    "DeviceGroupRef",
    "DeviceGroupRequest",
    "DeviceManagement",
    "DeviceManagementStatus",
    "DeviceManagementSystem",
    "DeviceManagementSystemInput",
    "DeviceManagementSystemSystem",
    "DeviceManufacturer",
    "DeviceOsType",
    "DevicePasswordPosture",
    "DevicePasswordPosturePolicy",
    "DevicePlatform",
    "DeviceRestoreResponse",
    "DeviceResumeResponse",
    "DeviceScreenLockStatus",
    "DeviceStatus",
    "DeviceStatusChangeRequest",
    "DeviceSuspendResponse",
    "DeviceType",
    "DiskEncryptionProduct",
    "DiskEncryptionVendorName",
    "DnsOverHttpsControl",
    "DnsOverHttpsControlAction",
    "DnsOverHttpsControlFailureMode",
    "EPP",
    "EnableDisableControl",
    "EnableDisableControlAction",
    "EnhancedTrackingProtectionControl",
    "EnhancedTrackingProtectionControlAction",
    "EppVendorName",
    "ErrorResponse",
    "ExternalApplicationLaunchException",
    "ExternalApplicationLaunchExceptionAction",
    "FirewallProduct",
    "FirewallVendorName",
    "FlushBrowserDataControl",
    "FlushBrowserDataControlAction",
    "FlushBrowserDataControlDataTypesInner",
    "FlushBrowserDataControlTrigger",
    "ForceHttpsControl",
    "ForceHttpsControlAction",
    "GetScope",
    "GetScopeDeviceGroups",
    "GetScopeLocations",
    "GetScopePrivateIps",
    "GetScopePublicIps",
    "GetScopeUsers",
    "GetSignInPolicy200Response",
    "InternetExplorerCompatibilityModeControl",
    "InternetExplorerCompatibilitySite",
    "InternetExplorerCompatibilitySiteDocumentMode",
    "IssuerCertificate",
    "JavaScriptV8JitAndWebAssemblyControl",
    "JavaScriptV8JitAndWebAssemblyControlAction",
    "KerberosDelegationAllowlistControl",
    "KerberosDelegationAllowlistControlAction",
    "KeyloggingProtectionControl",
    "KeyloggingProtectionControlAction",
    "LastDefinitionUpdateAttribute",
    "LaunchingExternalApplicationsControl",
    "LaunchingExternalApplicationsControlAction",
    "LegacyPasswordManagerControl",
    "LegacyPasswordManagerControlAction",
    "LegacyPasswordManagerControlMfaPromptFrequencyMinutes",
    "LinuxDistro",
    "LinuxVersion",
    "LinuxVersionAttribute",
    "ListApplicationCategories200Response",
    "ListApplicationGroups200Response",
    "ListApplicationGroupsSortParameter",
    "ListApplicationPlugins200Response",
    "ListApplications200Response",
    "ListApplicationsSortParameter",
    "ListApplicationsTypeParameter",
    "ListDeviceGroups200Response",
    "ListDeviceGroupsSortParameter",
    "ListDevices200Response",
    "ListDevicesSortParameter",
    "ListUserGroups200Response",
    "ListUserRequests200Response",
    "ListUserRequestsRequestStatusParameter",
    "ListUserRequestsRequestTypeParameter",
    "ListUserRequestsSortParameter",
    "ListUsers200Response",
    "ListUsersSortParameter",
    "LocalDesktopAppExecutableInput",
    "LocalDesktopAppExecutablesInput",
    "LocalDesktopApplication",
    "LocalDesktopApplicationAllOfExecutables",
    "LocalDesktopApplicationAllOfExecutablesData",
    "LocalDesktopApplicationAllOfType",
    "LocalDesktopApplicationInput",
    "LocalDesktopPatchApplicationInput",
    "LocalDesktopTypeInput",
    "LocalNetworkAccessRestrictionsControl",
    "LocalNetworkAccessRestrictionsControlAction",
    "LocationMethod",
    "Locations",
    "MacOSFileExistenceMetadata",
    "MacOSRunningProcessMetadata",
    "MacOSVersion",
    "MacOSVersionAttribute",
    "ManagementSystemType",
    "Metadata",
    "MetadataConfigurationVersion",
    "MetadataConfigurationVersionStatus",
    "MobileDeviceManagementSystem",
    "MobileDeviceManagementSystemName",
    "MobileDeviceType",
    "MobileManufacturer",
    "MobileOs",
    "MobileOsVersion",
    "NativeMessagingHostsControl",
    "NativeMessagingHostsControlAction",
    "NonWebApplication",
    "NonWebApplicationAllOfType",
    "NonWebApplicationInput",
    "NonWebPatchApplicationInput",
    "NonwebTypeInput",
    "NotificationsControl",
    "NotificationsControlAction",
    "OpenLinksInExternalAppsControl",
    "OpenLinksInExternalAppsControlAction",
    "OpenLinksInExternalAppsControlAllowedAppsInner",
    "Order",
    "OsPasswordComplexity",
    "PageInfo",
    "PagesWithInsecureContentControl",
    "PagesWithInsecureContentControlAction",
    "PatchAppGroupInput",
    "PatchAppGroupInputApplications",
    "PatchAppInput",
    "PatchApplicationByTypeAndID200Response",
    "PatchCidrs",
    "PatchCustomizationRuleByIDRequest",
    "PatchPositionsRequest",
    "PatchScope",
    "PatchScopeDeviceGroups",
    "PatchScopeLocations",
    "PatchScopePrivateIps",
    "PatchScopePublicIps",
    "PatchScopeUsers",
    "PatchSecurityRuleByID200Response",
    "PatchSecurityRuleByIDRequest",
    "PatchSignInRuleByID200Response",
    "PatchSignInRuleByIDRequest",
    "PatchUrls",
    "Plugin",
    "PluginElement",
    "PluginElementElementType",
    "PluginEvent",
    "PluginEventEventType",
    "PluginEventHeadersInner",
    "PluginEventMethod",
    "PluginLink",
    "PluginResponse",
    "PolicyItem",
    "PolicyPositioning",
    "PolicyPositioningTarget",
    "PolicyPositioningTargetAnchor",
    "PolicyPositioningTargetAnchorType",
    "PolicyPositioningTargetPosition",
    "PopupsControl",
    "PopupsControlAction",
    "PositionItem",
    "PositionItemRule",
    "PositionItemRuleType",
    "PositionItemSection",
    "PositionItemSectionType",
    "PositionMove",
    "PositionMoveSubject",
    "PositionMoveSubjectType",
    "PositionMoveTarget",
    "PositionMoveTargetAnchor",
    "PositionMoveTargetAnchorType",
    "PositionMoveTargetPosition",
    "PositionsSuccessResponse",
    "PostQuantumKeySecurityControl",
    "PostQuantumKeySecurityControlAction",
    "PostScope",
    "PostScopeDeviceGroups",
    "PostScopeLocations",
    "PostScopePrivateIps",
    "PostScopePublicIps",
    "PostScopeUsers",
    "PrivateApplication",
    "PrivateApplicationAllOfType",
    "PrivateApplicationInput",
    "PrivatePatchApplicationInput",
    "PrivateTypeInput",
    "PublishDraftConfiguration409Response",
    "PublishDraftConfiguration501Response",
    "PublishDraftConfigurationRequest",
    "RegKey",
    "RegValue",
    "RegistryValueType",
    "RequestAction",
    "RequestActionAction",
    "RequestActionAdminBypassTimeframe",
    "RequestError",
    "ResponseMetadata",
    "RestrictExtensionHostPermissionsControl",
    "RestrictExtensionHostPermissionsControlAction",
    "RevokeRequestAction",
    "RuleMode",
    "RuleSummary",
    "RuleSummaryAllOfType",
    "Section",
    "SectionAllOfType",
    "SectionDetailed",
    "SectionPatchRequest",
    "SectionPostRequest",
    "SectionRef",
    "SectionUpdateRequest",
    "SecurityControls",
    "SecurityRuleDetailed",
    "SelectedDeviceVendor",
    "SessionRefreshControl",
    "SessionRefreshControlAction",
    "SessionRefreshControlMaxSessionDuration",
    "SignInRuleAction",
    "SignInRuleDetailed",
    "SignInRuleDetailedAction",
    "SignInRuleDetailedActionAction",
    "SuspendUsers400Response",
    "SystemIntegrityPosture",
    "SystemIntegrityPostureServices",
    "SystemIntegrityPostureStatus",
    "TrustedCertificateAuthoritiesControl",
    "TrustedCertificateAuthoritiesControlMode",
    "TrustedCertificateEntry",
    "UpdateApplicationPlugin200Response",
    "UpdateApplicationPluginRequest",
    "UpdateDeviceGroup200Response",
    "UpdateSignInPositionsRequest",
    "UpdateSignInSectionByID200Response",
    "UpdateUserGroup200Response",
    "UpdateUserGroupRequest",
    "UpdateUserGroupRequestUsersInner",
    "UpdateUserGroupRequestUsersInnerAction",
    "UrlInput",
    "User",
    "UserForceReauthResponse",
    "UserGroup",
    "UserGroupProvider",
    "UserGroupRef",
    "UserProvider",
    "UserRef",
    "UserRequest",
    "UserRequestRemoteApplication",
    "UserResumeResponse",
    "UserStatus",
    "UserStatusChangeRequest",
    "UserSuspendResponse",
    "WebRtcControl",
    "WebRtcControlAction",
    "WinFileExistenceMetadata",
    "WinRunningProcessMetadata",
    "WindowsEdition",
    "WindowsVersion",
    "WindowsVersionAttribute",
]

# import apis into sdk package
from prisma_browser.api.access_and_data_policy_api import AccessAndDataPolicyApi as AccessAndDataPolicyApi
from prisma_browser.api.application_groups_api import ApplicationGroupsApi as ApplicationGroupsApi
from prisma_browser.api.applications_api import ApplicationsApi as ApplicationsApi
from prisma_browser.api.configuration_management_api import ConfigurationManagementApi as ConfigurationManagementApi
from prisma_browser.api.customization_policy_api import CustomizationPolicyApi as CustomizationPolicyApi
from prisma_browser.api.device_groups_api import DeviceGroupsApi as DeviceGroupsApi
from prisma_browser.api.devices_api import DevicesApi as DevicesApi
from prisma_browser.api.plugins_api import PluginsApi as PluginsApi
from prisma_browser.api.security_policy_api import SecurityPolicyApi as SecurityPolicyApi
from prisma_browser.api.sign_in_policy_api import SignInPolicyApi as SignInPolicyApi
from prisma_browser.api.user_groups_api import UserGroupsApi as UserGroupsApi
from prisma_browser.api.user_requests_api import UserRequestsApi as UserRequestsApi
from prisma_browser.api.users_api import UsersApi as UsersApi

# import ApiClient
from prisma_browser.api_response import ApiResponse as ApiResponse
from prisma_browser.api_client import ApiClient as ApiClient
from prisma_browser.configuration import Configuration as Configuration
from prisma_browser.exceptions import OpenApiException as OpenApiException
from prisma_browser.exceptions import ApiTypeError as ApiTypeError
from prisma_browser.exceptions import ApiValueError as ApiValueError
from prisma_browser.exceptions import ApiKeyError as ApiKeyError
from prisma_browser.exceptions import ApiAttributeError as ApiAttributeError
from prisma_browser.exceptions import ApiException as ApiException

# import models into sdk package
from prisma_browser.models.access_and_data_rule_detailed import AccessAndDataRuleDetailed as AccessAndDataRuleDetailed
from prisma_browser.models.access_and_data_rule_detailed_metadata import AccessAndDataRuleDetailedMetadata as AccessAndDataRuleDetailedMetadata
from prisma_browser.models.access_and_data_rule_mode import AccessAndDataRuleMode as AccessAndDataRuleMode
from prisma_browser.models.add_remove_apps import AddRemoveApps as AddRemoveApps
from prisma_browser.models.add_remove_cidrs import AddRemoveCidrs as AddRemoveCidrs
from prisma_browser.models.add_remove_urls import AddRemoveUrls as AddRemoveUrls
from prisma_browser.models.allow_block_control import AllowBlockControl as AllowBlockControl
from prisma_browser.models.allow_block_control_action import AllowBlockControlAction as AllowBlockControlAction
from prisma_browser.models.allowed_or_blocked_extension_entry import AllowedOrBlockedExtensionEntry as AllowedOrBlockedExtensionEntry
from prisma_browser.models.allowed_or_blocked_extensions_control import AllowedOrBlockedExtensionsControl as AllowedOrBlockedExtensionsControl
from prisma_browser.models.allowed_or_blocked_extensions_control_mode import AllowedOrBlockedExtensionsControlMode as AllowedOrBlockedExtensionsControlMode
from prisma_browser.models.allowed_or_blocked_extensions_control_risk_level import AllowedOrBlockedExtensionsControlRiskLevel as AllowedOrBlockedExtensionsControlRiskLevel
from prisma_browser.models.allowed_printers_control import AllowedPrintersControl as AllowedPrintersControl
from prisma_browser.models.allowed_printers_control_action import AllowedPrintersControlAction as AllowedPrintersControlAction
from prisma_browser.models.api_error import ApiError as ApiError
from prisma_browser.models.api_error_error import ApiErrorError as ApiErrorError
from prisma_browser.models.api_error_error_code import ApiErrorErrorCode as ApiErrorErrorCode
from prisma_browser.models.api_error_error_details_inner import ApiErrorErrorDetailsInner as ApiErrorErrorDetailsInner
from prisma_browser.models.application_group import ApplicationGroup as ApplicationGroup
from prisma_browser.models.application_group_applications_inner import ApplicationGroupApplicationsInner as ApplicationGroupApplicationsInner
from prisma_browser.models.application_group_applications_inner_type import ApplicationGroupApplicationsInnerType as ApplicationGroupApplicationsInnerType
from prisma_browser.models.application_item import ApplicationItem as ApplicationItem
from prisma_browser.models.application_type_input import ApplicationTypeInput as ApplicationTypeInput
from prisma_browser.models.attribute_object import AttributeObject as AttributeObject
from prisma_browser.models.attribute_object_browser_brand import AttributeObjectBrowserBrand as AttributeObjectBrowserBrand
from prisma_browser.models.attribute_object_browser_eol import AttributeObjectBrowserEol as AttributeObjectBrowserEol
from prisma_browser.models.attribute_object_client_certificate import AttributeObjectClientCertificate as AttributeObjectClientCertificate
from prisma_browser.models.attribute_object_cs_zta_score import AttributeObjectCsZtaScore as AttributeObjectCsZtaScore
from prisma_browser.models.attribute_object_cs_zta_score_breakdown_scores import AttributeObjectCsZtaScoreBreakdownScores as AttributeObjectCsZtaScoreBreakdownScores
from prisma_browser.models.attribute_object_device_management import AttributeObjectDeviceManagement as AttributeObjectDeviceManagement
from prisma_browser.models.attribute_object_device_manufacturer import AttributeObjectDeviceManufacturer as AttributeObjectDeviceManufacturer
from prisma_browser.models.attribute_object_device_type import AttributeObjectDeviceType as AttributeObjectDeviceType
from prisma_browser.models.attribute_object_disk_encryption import AttributeObjectDiskEncryption as AttributeObjectDiskEncryption
from prisma_browser.models.attribute_object_endpoint_protection import AttributeObjectEndpointProtection as AttributeObjectEndpointProtection
from prisma_browser.models.attribute_object_file_existence import AttributeObjectFileExistence as AttributeObjectFileExistence
from prisma_browser.models.attribute_object_firewall import AttributeObjectFirewall as AttributeObjectFirewall
from prisma_browser.models.attribute_object_location_services import AttributeObjectLocationServices as AttributeObjectLocationServices
from prisma_browser.models.attribute_object_mobile_device_management import AttributeObjectMobileDeviceManagement as AttributeObjectMobileDeviceManagement
from prisma_browser.models.attribute_object_mobile_device_manufacturers import AttributeObjectMobileDeviceManufacturers as AttributeObjectMobileDeviceManufacturers
from prisma_browser.models.attribute_object_mobile_device_type import AttributeObjectMobileDeviceType as AttributeObjectMobileDeviceType
from prisma_browser.models.attribute_object_mobile_os_version import AttributeObjectMobileOsVersion as AttributeObjectMobileOsVersion
from prisma_browser.models.attribute_object_mobile_root_jail_break_status import AttributeObjectMobileRootJailBreakStatus as AttributeObjectMobileRootJailBreakStatus
from prisma_browser.models.attribute_object_mobile_screen_lock import AttributeObjectMobileScreenLock as AttributeObjectMobileScreenLock
from prisma_browser.models.attribute_object_normal_os_boot_mode import AttributeObjectNormalOSBootMode as AttributeObjectNormalOSBootMode
from prisma_browser.models.attribute_object_os_password import AttributeObjectOsPassword as AttributeObjectOsPassword
from prisma_browser.models.attribute_object_os_version import AttributeObjectOsVersion as AttributeObjectOsVersion
from prisma_browser.models.attribute_object_privileged_process import AttributeObjectPrivilegedProcess as AttributeObjectPrivilegedProcess
from prisma_browser.models.attribute_object_registry import AttributeObjectRegistry as AttributeObjectRegistry
from prisma_browser.models.attribute_object_remote_connection import AttributeObjectRemoteConnection as AttributeObjectRemoteConnection
from prisma_browser.models.attribute_object_running_processes import AttributeObjectRunningProcesses as AttributeObjectRunningProcesses
from prisma_browser.models.attribute_object_screen_lock import AttributeObjectScreenLock as AttributeObjectScreenLock
from prisma_browser.models.attribute_object_serial_number import AttributeObjectSerialNumber as AttributeObjectSerialNumber
from prisma_browser.models.attribute_object_system_integrity import AttributeObjectSystemIntegrity as AttributeObjectSystemIntegrity
from prisma_browser.models.authentication_factor_control import AuthenticationFactorControl as AuthenticationFactorControl
from prisma_browser.models.authentication_factor_identity_provider_control import AuthenticationFactorIdentityProviderControl as AuthenticationFactorIdentityProviderControl
from prisma_browser.models.authentication_factor_identity_provider_control_identity_provider import AuthenticationFactorIdentityProviderControlIdentityProvider as AuthenticationFactorIdentityProviderControlIdentityProvider
from prisma_browser.models.authentication_factor_identity_provider_control_identity_provider_profile_source import AuthenticationFactorIdentityProviderControlIdentityProviderProfileSource as AuthenticationFactorIdentityProviderControlIdentityProviderProfileSource
from prisma_browser.models.authentication_factor_identity_provider_control_method import AuthenticationFactorIdentityProviderControlMethod as AuthenticationFactorIdentityProviderControlMethod
from prisma_browser.models.authentication_factor_passkey_control import AuthenticationFactorPasskeyControl as AuthenticationFactorPasskeyControl
from prisma_browser.models.authentication_factor_passkey_control_method import AuthenticationFactorPasskeyControlMethod as AuthenticationFactorPasskeyControlMethod
from prisma_browser.models.authentication_factor_passkey_control_passkey import AuthenticationFactorPasskeyControlPasskey as AuthenticationFactorPasskeyControlPasskey
from prisma_browser.models.authentication_factor_pin_code_control import AuthenticationFactorPinCodeControl as AuthenticationFactorPinCodeControl
from prisma_browser.models.authentication_factor_pin_code_control_method import AuthenticationFactorPinCodeControlMethod as AuthenticationFactorPinCodeControlMethod
from prisma_browser.models.authentication_factor_pin_code_control_pin_code import AuthenticationFactorPinCodeControlPinCode as AuthenticationFactorPinCodeControlPinCode
from prisma_browser.models.authentication_factor_pin_code_control_pin_code_max_failed_attempts import AuthenticationFactorPinCodeControlPinCodeMaxFailedAttempts as AuthenticationFactorPinCodeControlPinCodeMaxFailedAttempts
from prisma_browser.models.authentication_server_allowlist_control import AuthenticationServerAllowlistControl as AuthenticationServerAllowlistControl
from prisma_browser.models.authentication_server_allowlist_control_action import AuthenticationServerAllowlistControlAction as AuthenticationServerAllowlistControlAction
from prisma_browser.models.base_application import BaseApplication as BaseApplication
from prisma_browser.models.base_application_input import BaseApplicationInput as BaseApplicationInput
from prisma_browser.models.base_application_with_urls import BaseApplicationWithUrls as BaseApplicationWithUrls
from prisma_browser.models.base_patch_application_input import BasePatchApplicationInput as BasePatchApplicationInput
from prisma_browser.models.base_patch_rule_request import BasePatchRuleRequest as BasePatchRuleRequest
from prisma_browser.models.base_policy_item import BasePolicyItem as BasePolicyItem
from prisma_browser.models.base_post_rule_request import BasePostRuleRequest as BasePostRuleRequest
from prisma_browser.models.block_extensions_by_permissions_control import BlockExtensionsByPermissionsControl as BlockExtensionsByPermissionsControl
from prisma_browser.models.block_extensions_by_permissions_control_action import BlockExtensionsByPermissionsControlAction as BlockExtensionsByPermissionsControlAction
from prisma_browser.models.block_extensions_by_permissions_control_blocked_permissions_inner import BlockExtensionsByPermissionsControlBlockedPermissionsInner as BlockExtensionsByPermissionsControlBlockedPermissionsInner
from prisma_browser.models.browser_brand import BrowserBrand as BrowserBrand
from prisma_browser.models.browser_brand_details import BrowserBrandDetails as BrowserBrandDetails
from prisma_browser.models.browser_history_control import BrowserHistoryControl as BrowserHistoryControl
from prisma_browser.models.browser_history_control_action import BrowserHistoryControlAction as BrowserHistoryControlAction
from prisma_browser.models.browser_lock_control import BrowserLockControl as BrowserLockControl
from prisma_browser.models.browser_lock_control_action import BrowserLockControlAction as BrowserLockControlAction
from prisma_browser.models.browser_lock_control_idle_timeout_minutes import BrowserLockControlIdleTimeoutMinutes as BrowserLockControlIdleTimeoutMinutes
from prisma_browser.models.browser_self_protection_control import BrowserSelfProtectionControl as BrowserSelfProtectionControl
from prisma_browser.models.browser_self_protection_control_action import BrowserSelfProtectionControlAction as BrowserSelfProtectionControlAction
from prisma_browser.models.browser_self_protection_control_enforcement import BrowserSelfProtectionControlEnforcement as BrowserSelfProtectionControlEnforcement
from prisma_browser.models.browser_self_protection_module import BrowserSelfProtectionModule as BrowserSelfProtectionModule
from prisma_browser.models.browser_self_protection_module_windows import BrowserSelfProtectionModuleWindows as BrowserSelfProtectionModuleWindows
from prisma_browser.models.browser_self_protection_windows_driver_status import BrowserSelfProtectionWindowsDriverStatus as BrowserSelfProtectionWindowsDriverStatus
from prisma_browser.models.bulk_created_item import BulkCreatedItem as BulkCreatedItem
from prisma_browser.models.bulk_delete_applications_request import BulkDeleteApplicationsRequest as BulkDeleteApplicationsRequest
from prisma_browser.models.catalog_application import CatalogApplication as CatalogApplication
from prisma_browser.models.catalog_application_all_of_type import CatalogApplicationAllOfType as CatalogApplicationAllOfType
from prisma_browser.models.catalog_attributes import CatalogAttributes as CatalogAttributes
from prisma_browser.models.certificate_dn import CertificateDN as CertificateDN
from prisma_browser.models.concurrent_number_of_devices_control import ConcurrentNumberOfDevicesControl as ConcurrentNumberOfDevicesControl
from prisma_browser.models.concurrent_number_of_devices_control_action import ConcurrentNumberOfDevicesControlAction as ConcurrentNumberOfDevicesControlAction
from prisma_browser.models.concurrent_number_of_devices_control_limit_mode import ConcurrentNumberOfDevicesControlLimitMode as ConcurrentNumberOfDevicesControlLimitMode
from prisma_browser.models.cookies_control import CookiesControl as CookiesControl
from prisma_browser.models.cookies_control_action import CookiesControlAction as CookiesControlAction
from prisma_browser.models.create_access_and_data_rule_request import CreateAccessAndDataRuleRequest as CreateAccessAndDataRuleRequest
from prisma_browser.models.create_application201_response import CreateApplication201Response as CreateApplication201Response
from prisma_browser.models.create_application_plugin201_response import CreateApplicationPlugin201Response as CreateApplicationPlugin201Response
from prisma_browser.models.create_customization_rule_request import CreateCustomizationRuleRequest as CreateCustomizationRuleRequest
from prisma_browser.models.create_device_group201_response import CreateDeviceGroup201Response as CreateDeviceGroup201Response
from prisma_browser.models.create_or_replace_app_group_input import CreateOrReplaceAppGroupInput as CreateOrReplaceAppGroupInput
from prisma_browser.models.create_or_replace_app_input import CreateOrReplaceAppInput as CreateOrReplaceAppInput
from prisma_browser.models.create_security_rule201_response import CreateSecurityRule201Response as CreateSecurityRule201Response
from prisma_browser.models.create_security_rule_request import CreateSecurityRuleRequest as CreateSecurityRuleRequest
from prisma_browser.models.create_sign_in_rule_request import CreateSignInRuleRequest as CreateSignInRuleRequest
from prisma_browser.models.create_user_group201_response import CreateUserGroup201Response as CreateUserGroup201Response
from prisma_browser.models.create_user_group_request import CreateUserGroupRequest as CreateUserGroupRequest
from prisma_browser.models.crowdstrike_zta_posture import CrowdstrikeZTAPosture as CrowdstrikeZTAPosture
from prisma_browser.models.cs_zta_basic_score_level import CsZtaBasicScoreLevel as CsZtaBasicScoreLevel
from prisma_browser.models.cs_zta_score import CsZtaScore as CsZtaScore
from prisma_browser.models.custom_application import CustomApplication as CustomApplication
from prisma_browser.models.custom_application_all_of_type import CustomApplicationAllOfType as CustomApplicationAllOfType
from prisma_browser.models.custom_application_input import CustomApplicationInput as CustomApplicationInput
from prisma_browser.models.custom_patch_application_input import CustomPatchApplicationInput as CustomPatchApplicationInput
from prisma_browser.models.custom_type_input import CustomTypeInput as CustomTypeInput
from prisma_browser.models.customization_rule_detailed import CustomizationRuleDetailed as CustomizationRuleDetailed
from prisma_browser.models.definition_update_timeframe import DefinitionUpdateTimeframe as DefinitionUpdateTimeframe
from prisma_browser.models.delete_application_plugin200_response import DeleteApplicationPlugin200Response as DeleteApplicationPlugin200Response
from prisma_browser.models.delete_user_group200_response import DeleteUserGroup200Response as DeleteUserGroup200Response
from prisma_browser.models.device import Device as Device
from prisma_browser.models.device_archive_response import DeviceArchiveResponse as DeviceArchiveResponse
from prisma_browser.models.device_browser_brand import DeviceBrowserBrand as DeviceBrowserBrand
from prisma_browser.models.device_delete_response import DeviceDeleteResponse as DeviceDeleteResponse
from prisma_browser.models.device_device_type import DeviceDeviceType as DeviceDeviceType
from prisma_browser.models.device_disk_encryption_details import DeviceDiskEncryptionDetails as DeviceDiskEncryptionDetails
from prisma_browser.models.device_disk_encryption_status import DeviceDiskEncryptionStatus as DeviceDiskEncryptionStatus
from prisma_browser.models.device_epp import DeviceEPP as DeviceEPP
from prisma_browser.models.device_firewall_details import DeviceFirewallDetails as DeviceFirewallDetails
from prisma_browser.models.device_firewall_status import DeviceFirewallStatus as DeviceFirewallStatus
from prisma_browser.models.device_force_reauth_response import DeviceForceReauthResponse as DeviceForceReauthResponse
from prisma_browser.models.device_group import DeviceGroup as DeviceGroup
from prisma_browser.models.device_group_patch_request import DeviceGroupPatchRequest as DeviceGroupPatchRequest
from prisma_browser.models.device_group_platform import DeviceGroupPlatform as DeviceGroupPlatform
from prisma_browser.models.device_group_ref import DeviceGroupRef as DeviceGroupRef
from prisma_browser.models.device_group_request import DeviceGroupRequest as DeviceGroupRequest
from prisma_browser.models.device_management import DeviceManagement as DeviceManagement
from prisma_browser.models.device_management_status import DeviceManagementStatus as DeviceManagementStatus
from prisma_browser.models.device_management_system import DeviceManagementSystem as DeviceManagementSystem
from prisma_browser.models.device_management_system_input import DeviceManagementSystemInput as DeviceManagementSystemInput
from prisma_browser.models.device_management_system_system import DeviceManagementSystemSystem as DeviceManagementSystemSystem
from prisma_browser.models.device_manufacturer import DeviceManufacturer as DeviceManufacturer
from prisma_browser.models.device_os_type import DeviceOsType as DeviceOsType
from prisma_browser.models.device_password_posture import DevicePasswordPosture as DevicePasswordPosture
from prisma_browser.models.device_password_posture_policy import DevicePasswordPosturePolicy as DevicePasswordPosturePolicy
from prisma_browser.models.device_platform import DevicePlatform as DevicePlatform
from prisma_browser.models.device_restore_response import DeviceRestoreResponse as DeviceRestoreResponse
from prisma_browser.models.device_resume_response import DeviceResumeResponse as DeviceResumeResponse
from prisma_browser.models.device_screen_lock_status import DeviceScreenLockStatus as DeviceScreenLockStatus
from prisma_browser.models.device_status import DeviceStatus as DeviceStatus
from prisma_browser.models.device_status_change_request import DeviceStatusChangeRequest as DeviceStatusChangeRequest
from prisma_browser.models.device_suspend_response import DeviceSuspendResponse as DeviceSuspendResponse
from prisma_browser.models.device_type import DeviceType as DeviceType
from prisma_browser.models.disk_encryption_product import DiskEncryptionProduct as DiskEncryptionProduct
from prisma_browser.models.disk_encryption_vendor_name import DiskEncryptionVendorName as DiskEncryptionVendorName
from prisma_browser.models.dns_over_https_control import DnsOverHttpsControl as DnsOverHttpsControl
from prisma_browser.models.dns_over_https_control_action import DnsOverHttpsControlAction as DnsOverHttpsControlAction
from prisma_browser.models.dns_over_https_control_failure_mode import DnsOverHttpsControlFailureMode as DnsOverHttpsControlFailureMode
from prisma_browser.models.epp import EPP as EPP
from prisma_browser.models.enable_disable_control import EnableDisableControl as EnableDisableControl
from prisma_browser.models.enable_disable_control_action import EnableDisableControlAction as EnableDisableControlAction
from prisma_browser.models.enhanced_tracking_protection_control import EnhancedTrackingProtectionControl as EnhancedTrackingProtectionControl
from prisma_browser.models.enhanced_tracking_protection_control_action import EnhancedTrackingProtectionControlAction as EnhancedTrackingProtectionControlAction
from prisma_browser.models.epp_vendor_name import EppVendorName as EppVendorName
from prisma_browser.models.error_response import ErrorResponse as ErrorResponse
from prisma_browser.models.external_application_launch_exception import ExternalApplicationLaunchException as ExternalApplicationLaunchException
from prisma_browser.models.external_application_launch_exception_action import ExternalApplicationLaunchExceptionAction as ExternalApplicationLaunchExceptionAction
from prisma_browser.models.firewall_product import FirewallProduct as FirewallProduct
from prisma_browser.models.firewall_vendor_name import FirewallVendorName as FirewallVendorName
from prisma_browser.models.flush_browser_data_control import FlushBrowserDataControl as FlushBrowserDataControl
from prisma_browser.models.flush_browser_data_control_action import FlushBrowserDataControlAction as FlushBrowserDataControlAction
from prisma_browser.models.flush_browser_data_control_data_types_inner import FlushBrowserDataControlDataTypesInner as FlushBrowserDataControlDataTypesInner
from prisma_browser.models.flush_browser_data_control_trigger import FlushBrowserDataControlTrigger as FlushBrowserDataControlTrigger
from prisma_browser.models.force_https_control import ForceHttpsControl as ForceHttpsControl
from prisma_browser.models.force_https_control_action import ForceHttpsControlAction as ForceHttpsControlAction
from prisma_browser.models.get_scope import GetScope as GetScope
from prisma_browser.models.get_scope_device_groups import GetScopeDeviceGroups as GetScopeDeviceGroups
from prisma_browser.models.get_scope_locations import GetScopeLocations as GetScopeLocations
from prisma_browser.models.get_scope_private_ips import GetScopePrivateIps as GetScopePrivateIps
from prisma_browser.models.get_scope_public_ips import GetScopePublicIps as GetScopePublicIps
from prisma_browser.models.get_scope_users import GetScopeUsers as GetScopeUsers
from prisma_browser.models.get_sign_in_policy200_response import GetSignInPolicy200Response as GetSignInPolicy200Response
from prisma_browser.models.internet_explorer_compatibility_mode_control import InternetExplorerCompatibilityModeControl as InternetExplorerCompatibilityModeControl
from prisma_browser.models.internet_explorer_compatibility_site import InternetExplorerCompatibilitySite as InternetExplorerCompatibilitySite
from prisma_browser.models.internet_explorer_compatibility_site_document_mode import InternetExplorerCompatibilitySiteDocumentMode as InternetExplorerCompatibilitySiteDocumentMode
from prisma_browser.models.issuer_certificate import IssuerCertificate as IssuerCertificate
from prisma_browser.models.java_script_v8_jit_and_web_assembly_control import JavaScriptV8JitAndWebAssemblyControl as JavaScriptV8JitAndWebAssemblyControl
from prisma_browser.models.java_script_v8_jit_and_web_assembly_control_action import JavaScriptV8JitAndWebAssemblyControlAction as JavaScriptV8JitAndWebAssemblyControlAction
from prisma_browser.models.kerberos_delegation_allowlist_control import KerberosDelegationAllowlistControl as KerberosDelegationAllowlistControl
from prisma_browser.models.kerberos_delegation_allowlist_control_action import KerberosDelegationAllowlistControlAction as KerberosDelegationAllowlistControlAction
from prisma_browser.models.keylogging_protection_control import KeyloggingProtectionControl as KeyloggingProtectionControl
from prisma_browser.models.keylogging_protection_control_action import KeyloggingProtectionControlAction as KeyloggingProtectionControlAction
from prisma_browser.models.last_definition_update_attribute import LastDefinitionUpdateAttribute as LastDefinitionUpdateAttribute
from prisma_browser.models.launching_external_applications_control import LaunchingExternalApplicationsControl as LaunchingExternalApplicationsControl
from prisma_browser.models.launching_external_applications_control_action import LaunchingExternalApplicationsControlAction as LaunchingExternalApplicationsControlAction
from prisma_browser.models.legacy_password_manager_control import LegacyPasswordManagerControl as LegacyPasswordManagerControl
from prisma_browser.models.legacy_password_manager_control_action import LegacyPasswordManagerControlAction as LegacyPasswordManagerControlAction
from prisma_browser.models.legacy_password_manager_control_mfa_prompt_frequency_minutes import LegacyPasswordManagerControlMfaPromptFrequencyMinutes as LegacyPasswordManagerControlMfaPromptFrequencyMinutes
from prisma_browser.models.linux_distro import LinuxDistro as LinuxDistro
from prisma_browser.models.linux_version import LinuxVersion as LinuxVersion
from prisma_browser.models.linux_version_attribute import LinuxVersionAttribute as LinuxVersionAttribute
from prisma_browser.models.list_application_categories200_response import ListApplicationCategories200Response as ListApplicationCategories200Response
from prisma_browser.models.list_application_groups200_response import ListApplicationGroups200Response as ListApplicationGroups200Response
from prisma_browser.models.list_application_groups_sort_parameter import ListApplicationGroupsSortParameter as ListApplicationGroupsSortParameter
from prisma_browser.models.list_application_plugins200_response import ListApplicationPlugins200Response as ListApplicationPlugins200Response
from prisma_browser.models.list_applications200_response import ListApplications200Response as ListApplications200Response
from prisma_browser.models.list_applications_sort_parameter import ListApplicationsSortParameter as ListApplicationsSortParameter
from prisma_browser.models.list_applications_type_parameter import ListApplicationsTypeParameter as ListApplicationsTypeParameter
from prisma_browser.models.list_device_groups200_response import ListDeviceGroups200Response as ListDeviceGroups200Response
from prisma_browser.models.list_device_groups_sort_parameter import ListDeviceGroupsSortParameter as ListDeviceGroupsSortParameter
from prisma_browser.models.list_devices200_response import ListDevices200Response as ListDevices200Response
from prisma_browser.models.list_devices_sort_parameter import ListDevicesSortParameter as ListDevicesSortParameter
from prisma_browser.models.list_user_groups200_response import ListUserGroups200Response as ListUserGroups200Response
from prisma_browser.models.list_user_requests200_response import ListUserRequests200Response as ListUserRequests200Response
from prisma_browser.models.list_user_requests_request_status_parameter import ListUserRequestsRequestStatusParameter as ListUserRequestsRequestStatusParameter
from prisma_browser.models.list_user_requests_request_type_parameter import ListUserRequestsRequestTypeParameter as ListUserRequestsRequestTypeParameter
from prisma_browser.models.list_user_requests_sort_parameter import ListUserRequestsSortParameter as ListUserRequestsSortParameter
from prisma_browser.models.list_users200_response import ListUsers200Response as ListUsers200Response
from prisma_browser.models.list_users_sort_parameter import ListUsersSortParameter as ListUsersSortParameter
from prisma_browser.models.local_desktop_app_executable_input import LocalDesktopAppExecutableInput as LocalDesktopAppExecutableInput
from prisma_browser.models.local_desktop_app_executables_input import LocalDesktopAppExecutablesInput as LocalDesktopAppExecutablesInput
from prisma_browser.models.local_desktop_application import LocalDesktopApplication as LocalDesktopApplication
from prisma_browser.models.local_desktop_application_all_of_executables import LocalDesktopApplicationAllOfExecutables as LocalDesktopApplicationAllOfExecutables
from prisma_browser.models.local_desktop_application_all_of_executables_data import LocalDesktopApplicationAllOfExecutablesData as LocalDesktopApplicationAllOfExecutablesData
from prisma_browser.models.local_desktop_application_all_of_type import LocalDesktopApplicationAllOfType as LocalDesktopApplicationAllOfType
from prisma_browser.models.local_desktop_application_input import LocalDesktopApplicationInput as LocalDesktopApplicationInput
from prisma_browser.models.local_desktop_patch_application_input import LocalDesktopPatchApplicationInput as LocalDesktopPatchApplicationInput
from prisma_browser.models.local_desktop_type_input import LocalDesktopTypeInput as LocalDesktopTypeInput
from prisma_browser.models.local_network_access_restrictions_control import LocalNetworkAccessRestrictionsControl as LocalNetworkAccessRestrictionsControl
from prisma_browser.models.local_network_access_restrictions_control_action import LocalNetworkAccessRestrictionsControlAction as LocalNetworkAccessRestrictionsControlAction
from prisma_browser.models.location_method import LocationMethod as LocationMethod
from prisma_browser.models.locations import Locations as Locations
from prisma_browser.models.mac_os_file_existence_metadata import MacOSFileExistenceMetadata as MacOSFileExistenceMetadata
from prisma_browser.models.mac_os_running_process_metadata import MacOSRunningProcessMetadata as MacOSRunningProcessMetadata
from prisma_browser.models.mac_os_version import MacOSVersion as MacOSVersion
from prisma_browser.models.mac_os_version_attribute import MacOSVersionAttribute as MacOSVersionAttribute
from prisma_browser.models.management_system_type import ManagementSystemType as ManagementSystemType
from prisma_browser.models.metadata import Metadata as Metadata
from prisma_browser.models.metadata_configuration_version import MetadataConfigurationVersion as MetadataConfigurationVersion
from prisma_browser.models.metadata_configuration_version_status import MetadataConfigurationVersionStatus as MetadataConfigurationVersionStatus
from prisma_browser.models.mobile_device_management_system import MobileDeviceManagementSystem as MobileDeviceManagementSystem
from prisma_browser.models.mobile_device_management_system_name import MobileDeviceManagementSystemName as MobileDeviceManagementSystemName
from prisma_browser.models.mobile_device_type import MobileDeviceType as MobileDeviceType
from prisma_browser.models.mobile_manufacturer import MobileManufacturer as MobileManufacturer
from prisma_browser.models.mobile_os import MobileOs as MobileOs
from prisma_browser.models.mobile_os_version import MobileOsVersion as MobileOsVersion
from prisma_browser.models.native_messaging_hosts_control import NativeMessagingHostsControl as NativeMessagingHostsControl
from prisma_browser.models.native_messaging_hosts_control_action import NativeMessagingHostsControlAction as NativeMessagingHostsControlAction
from prisma_browser.models.non_web_application import NonWebApplication as NonWebApplication
from prisma_browser.models.non_web_application_all_of_type import NonWebApplicationAllOfType as NonWebApplicationAllOfType
from prisma_browser.models.non_web_application_input import NonWebApplicationInput as NonWebApplicationInput
from prisma_browser.models.non_web_patch_application_input import NonWebPatchApplicationInput as NonWebPatchApplicationInput
from prisma_browser.models.nonweb_type_input import NonwebTypeInput as NonwebTypeInput
from prisma_browser.models.notifications_control import NotificationsControl as NotificationsControl
from prisma_browser.models.notifications_control_action import NotificationsControlAction as NotificationsControlAction
from prisma_browser.models.open_links_in_external_apps_control import OpenLinksInExternalAppsControl as OpenLinksInExternalAppsControl
from prisma_browser.models.open_links_in_external_apps_control_action import OpenLinksInExternalAppsControlAction as OpenLinksInExternalAppsControlAction
from prisma_browser.models.open_links_in_external_apps_control_allowed_apps_inner import OpenLinksInExternalAppsControlAllowedAppsInner as OpenLinksInExternalAppsControlAllowedAppsInner
from prisma_browser.models.order import Order as Order
from prisma_browser.models.os_password_complexity import OsPasswordComplexity as OsPasswordComplexity
from prisma_browser.models.page_info import PageInfo as PageInfo
from prisma_browser.models.pages_with_insecure_content_control import PagesWithInsecureContentControl as PagesWithInsecureContentControl
from prisma_browser.models.pages_with_insecure_content_control_action import PagesWithInsecureContentControlAction as PagesWithInsecureContentControlAction
from prisma_browser.models.patch_app_group_input import PatchAppGroupInput as PatchAppGroupInput
from prisma_browser.models.patch_app_group_input_applications import PatchAppGroupInputApplications as PatchAppGroupInputApplications
from prisma_browser.models.patch_app_input import PatchAppInput as PatchAppInput
from prisma_browser.models.patch_application_by_type_and_id200_response import PatchApplicationByTypeAndID200Response as PatchApplicationByTypeAndID200Response
from prisma_browser.models.patch_cidrs import PatchCidrs as PatchCidrs
from prisma_browser.models.patch_customization_rule_by_id_request import PatchCustomizationRuleByIDRequest as PatchCustomizationRuleByIDRequest
from prisma_browser.models.patch_positions_request import PatchPositionsRequest as PatchPositionsRequest
from prisma_browser.models.patch_scope import PatchScope as PatchScope
from prisma_browser.models.patch_scope_device_groups import PatchScopeDeviceGroups as PatchScopeDeviceGroups
from prisma_browser.models.patch_scope_locations import PatchScopeLocations as PatchScopeLocations
from prisma_browser.models.patch_scope_private_ips import PatchScopePrivateIps as PatchScopePrivateIps
from prisma_browser.models.patch_scope_public_ips import PatchScopePublicIps as PatchScopePublicIps
from prisma_browser.models.patch_scope_users import PatchScopeUsers as PatchScopeUsers
from prisma_browser.models.patch_security_rule_by_id200_response import PatchSecurityRuleByID200Response as PatchSecurityRuleByID200Response
from prisma_browser.models.patch_security_rule_by_id_request import PatchSecurityRuleByIDRequest as PatchSecurityRuleByIDRequest
from prisma_browser.models.patch_sign_in_rule_by_id200_response import PatchSignInRuleByID200Response as PatchSignInRuleByID200Response
from prisma_browser.models.patch_sign_in_rule_by_id_request import PatchSignInRuleByIDRequest as PatchSignInRuleByIDRequest
from prisma_browser.models.patch_urls import PatchUrls as PatchUrls
from prisma_browser.models.plugin import Plugin as Plugin
from prisma_browser.models.plugin_element import PluginElement as PluginElement
from prisma_browser.models.plugin_element_element_type import PluginElementElementType as PluginElementElementType
from prisma_browser.models.plugin_event import PluginEvent as PluginEvent
from prisma_browser.models.plugin_event_event_type import PluginEventEventType as PluginEventEventType
from prisma_browser.models.plugin_event_headers_inner import PluginEventHeadersInner as PluginEventHeadersInner
from prisma_browser.models.plugin_event_method import PluginEventMethod as PluginEventMethod
from prisma_browser.models.plugin_link import PluginLink as PluginLink
from prisma_browser.models.plugin_response import PluginResponse as PluginResponse
from prisma_browser.models.policy_item import PolicyItem as PolicyItem
from prisma_browser.models.policy_positioning import PolicyPositioning as PolicyPositioning
from prisma_browser.models.policy_positioning_target import PolicyPositioningTarget as PolicyPositioningTarget
from prisma_browser.models.policy_positioning_target_anchor import PolicyPositioningTargetAnchor as PolicyPositioningTargetAnchor
from prisma_browser.models.policy_positioning_target_anchor_type import PolicyPositioningTargetAnchorType as PolicyPositioningTargetAnchorType
from prisma_browser.models.policy_positioning_target_position import PolicyPositioningTargetPosition as PolicyPositioningTargetPosition
from prisma_browser.models.popups_control import PopupsControl as PopupsControl
from prisma_browser.models.popups_control_action import PopupsControlAction as PopupsControlAction
from prisma_browser.models.position_item import PositionItem as PositionItem
from prisma_browser.models.position_item_rule import PositionItemRule as PositionItemRule
from prisma_browser.models.position_item_rule_type import PositionItemRuleType as PositionItemRuleType
from prisma_browser.models.position_item_section import PositionItemSection as PositionItemSection
from prisma_browser.models.position_item_section_type import PositionItemSectionType as PositionItemSectionType
from prisma_browser.models.position_move import PositionMove as PositionMove
from prisma_browser.models.position_move_subject import PositionMoveSubject as PositionMoveSubject
from prisma_browser.models.position_move_subject_type import PositionMoveSubjectType as PositionMoveSubjectType
from prisma_browser.models.position_move_target import PositionMoveTarget as PositionMoveTarget
from prisma_browser.models.position_move_target_anchor import PositionMoveTargetAnchor as PositionMoveTargetAnchor
from prisma_browser.models.position_move_target_anchor_type import PositionMoveTargetAnchorType as PositionMoveTargetAnchorType
from prisma_browser.models.position_move_target_position import PositionMoveTargetPosition as PositionMoveTargetPosition
from prisma_browser.models.positions_success_response import PositionsSuccessResponse as PositionsSuccessResponse
from prisma_browser.models.post_quantum_key_security_control import PostQuantumKeySecurityControl as PostQuantumKeySecurityControl
from prisma_browser.models.post_quantum_key_security_control_action import PostQuantumKeySecurityControlAction as PostQuantumKeySecurityControlAction
from prisma_browser.models.post_scope import PostScope as PostScope
from prisma_browser.models.post_scope_device_groups import PostScopeDeviceGroups as PostScopeDeviceGroups
from prisma_browser.models.post_scope_locations import PostScopeLocations as PostScopeLocations
from prisma_browser.models.post_scope_private_ips import PostScopePrivateIps as PostScopePrivateIps
from prisma_browser.models.post_scope_public_ips import PostScopePublicIps as PostScopePublicIps
from prisma_browser.models.post_scope_users import PostScopeUsers as PostScopeUsers
from prisma_browser.models.private_application import PrivateApplication as PrivateApplication
from prisma_browser.models.private_application_all_of_type import PrivateApplicationAllOfType as PrivateApplicationAllOfType
from prisma_browser.models.private_application_input import PrivateApplicationInput as PrivateApplicationInput
from prisma_browser.models.private_patch_application_input import PrivatePatchApplicationInput as PrivatePatchApplicationInput
from prisma_browser.models.private_type_input import PrivateTypeInput as PrivateTypeInput
from prisma_browser.models.publish_draft_configuration409_response import PublishDraftConfiguration409Response as PublishDraftConfiguration409Response
from prisma_browser.models.publish_draft_configuration501_response import PublishDraftConfiguration501Response as PublishDraftConfiguration501Response
from prisma_browser.models.publish_draft_configuration_request import PublishDraftConfigurationRequest as PublishDraftConfigurationRequest
from prisma_browser.models.reg_key import RegKey as RegKey
from prisma_browser.models.reg_value import RegValue as RegValue
from prisma_browser.models.registry_value_type import RegistryValueType as RegistryValueType
from prisma_browser.models.request_action import RequestAction as RequestAction
from prisma_browser.models.request_action_action import RequestActionAction as RequestActionAction
from prisma_browser.models.request_action_admin_bypass_timeframe import RequestActionAdminBypassTimeframe as RequestActionAdminBypassTimeframe
from prisma_browser.models.request_error import RequestError as RequestError
from prisma_browser.models.response_metadata import ResponseMetadata as ResponseMetadata
from prisma_browser.models.restrict_extension_host_permissions_control import RestrictExtensionHostPermissionsControl as RestrictExtensionHostPermissionsControl
from prisma_browser.models.restrict_extension_host_permissions_control_action import RestrictExtensionHostPermissionsControlAction as RestrictExtensionHostPermissionsControlAction
from prisma_browser.models.revoke_request_action import RevokeRequestAction as RevokeRequestAction
from prisma_browser.models.rule_mode import RuleMode as RuleMode
from prisma_browser.models.rule_summary import RuleSummary as RuleSummary
from prisma_browser.models.rule_summary_all_of_type import RuleSummaryAllOfType as RuleSummaryAllOfType
from prisma_browser.models.section import Section as Section
from prisma_browser.models.section_all_of_type import SectionAllOfType as SectionAllOfType
from prisma_browser.models.section_detailed import SectionDetailed as SectionDetailed
from prisma_browser.models.section_patch_request import SectionPatchRequest as SectionPatchRequest
from prisma_browser.models.section_post_request import SectionPostRequest as SectionPostRequest
from prisma_browser.models.section_ref import SectionRef as SectionRef
from prisma_browser.models.section_update_request import SectionUpdateRequest as SectionUpdateRequest
from prisma_browser.models.security_controls import SecurityControls as SecurityControls
from prisma_browser.models.security_rule_detailed import SecurityRuleDetailed as SecurityRuleDetailed
from prisma_browser.models.selected_device_vendor import SelectedDeviceVendor as SelectedDeviceVendor
from prisma_browser.models.session_refresh_control import SessionRefreshControl as SessionRefreshControl
from prisma_browser.models.session_refresh_control_action import SessionRefreshControlAction as SessionRefreshControlAction
from prisma_browser.models.session_refresh_control_max_session_duration import SessionRefreshControlMaxSessionDuration as SessionRefreshControlMaxSessionDuration
from prisma_browser.models.sign_in_rule_action import SignInRuleAction as SignInRuleAction
from prisma_browser.models.sign_in_rule_detailed import SignInRuleDetailed as SignInRuleDetailed
from prisma_browser.models.sign_in_rule_detailed_action import SignInRuleDetailedAction as SignInRuleDetailedAction
from prisma_browser.models.sign_in_rule_detailed_action_action import SignInRuleDetailedActionAction as SignInRuleDetailedActionAction
from prisma_browser.models.suspend_users400_response import SuspendUsers400Response as SuspendUsers400Response
from prisma_browser.models.system_integrity_posture import SystemIntegrityPosture as SystemIntegrityPosture
from prisma_browser.models.system_integrity_posture_services import SystemIntegrityPostureServices as SystemIntegrityPostureServices
from prisma_browser.models.system_integrity_posture_status import SystemIntegrityPostureStatus as SystemIntegrityPostureStatus
from prisma_browser.models.trusted_certificate_authorities_control import TrustedCertificateAuthoritiesControl as TrustedCertificateAuthoritiesControl
from prisma_browser.models.trusted_certificate_authorities_control_mode import TrustedCertificateAuthoritiesControlMode as TrustedCertificateAuthoritiesControlMode
from prisma_browser.models.trusted_certificate_entry import TrustedCertificateEntry as TrustedCertificateEntry
from prisma_browser.models.update_application_plugin200_response import UpdateApplicationPlugin200Response as UpdateApplicationPlugin200Response
from prisma_browser.models.update_application_plugin_request import UpdateApplicationPluginRequest as UpdateApplicationPluginRequest
from prisma_browser.models.update_device_group200_response import UpdateDeviceGroup200Response as UpdateDeviceGroup200Response
from prisma_browser.models.update_sign_in_positions_request import UpdateSignInPositionsRequest as UpdateSignInPositionsRequest
from prisma_browser.models.update_sign_in_section_by_id200_response import UpdateSignInSectionByID200Response as UpdateSignInSectionByID200Response
from prisma_browser.models.update_user_group200_response import UpdateUserGroup200Response as UpdateUserGroup200Response
from prisma_browser.models.update_user_group_request import UpdateUserGroupRequest as UpdateUserGroupRequest
from prisma_browser.models.update_user_group_request_users_inner import UpdateUserGroupRequestUsersInner as UpdateUserGroupRequestUsersInner
from prisma_browser.models.update_user_group_request_users_inner_action import UpdateUserGroupRequestUsersInnerAction as UpdateUserGroupRequestUsersInnerAction
from prisma_browser.models.url_input import UrlInput as UrlInput
from prisma_browser.models.user import User as User
from prisma_browser.models.user_force_reauth_response import UserForceReauthResponse as UserForceReauthResponse
from prisma_browser.models.user_group import UserGroup as UserGroup
from prisma_browser.models.user_group_provider import UserGroupProvider as UserGroupProvider
from prisma_browser.models.user_group_ref import UserGroupRef as UserGroupRef
from prisma_browser.models.user_provider import UserProvider as UserProvider
from prisma_browser.models.user_ref import UserRef as UserRef
from prisma_browser.models.user_request import UserRequest as UserRequest
from prisma_browser.models.user_request_remote_application import UserRequestRemoteApplication as UserRequestRemoteApplication
from prisma_browser.models.user_resume_response import UserResumeResponse as UserResumeResponse
from prisma_browser.models.user_status import UserStatus as UserStatus
from prisma_browser.models.user_status_change_request import UserStatusChangeRequest as UserStatusChangeRequest
from prisma_browser.models.user_suspend_response import UserSuspendResponse as UserSuspendResponse
from prisma_browser.models.web_rtc_control import WebRtcControl as WebRtcControl
from prisma_browser.models.web_rtc_control_action import WebRtcControlAction as WebRtcControlAction
from prisma_browser.models.win_file_existence_metadata import WinFileExistenceMetadata as WinFileExistenceMetadata
from prisma_browser.models.win_running_process_metadata import WinRunningProcessMetadata as WinRunningProcessMetadata
from prisma_browser.models.windows_edition import WindowsEdition as WindowsEdition
from prisma_browser.models.windows_version import WindowsVersion as WindowsVersion
from prisma_browser.models.windows_version_attribute import WindowsVersionAttribute as WindowsVersionAttribute

