# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from prisma_browser.models.allow_block_control import AllowBlockControl
from prisma_browser.models.clipboard_control import ClipboardControl
from prisma_browser.models.custom_http_header_control import CustomHttpHeaderControl
from prisma_browser.models.dlp_profile_ref import DlpProfileRef
from prisma_browser.models.file_protection_control import FileProtectionControl
from prisma_browser.models.form_submission_control import FormSubmissionControl
from prisma_browser.models.live_page_scanning_control import LivePageScanningControl
from prisma_browser.models.malicious_file_protection_control import MaliciousFileProtectionControl
from prisma_browser.models.print_control import PrintControl
from prisma_browser.models.sanitizing_content_control import SanitizingContentControl
from prisma_browser.models.screenshot_control import ScreenshotControl
from prisma_browser.models.user_agent_control import UserAgentControl
from prisma_browser.models.watermark_control import WatermarkControl
from prisma_browser.models.web_user_interaction_control import WebUserInteractionControl
from prisma_browser.models.webpage_data_masking_control import WebpageDataMaskingControl
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccessAndDataDataControls(BaseModel):
    """
    Data controls for access-and-data rules.  Each data control supports a specific set of data-profile content types (no profile, on-device scanning, or cloud-assisted scanning). When a rule links a data profile (an EDLP `dlpProfileId`) or uses inline content, controls that are not supported for the resulting content type are rejected with HTTP 400. Set `bypassDlpProfileValidation: true` to suppress content-agnostic compatibility rejections only — those controls save successfully but become runtime no-ops. Controls that are entirely unsupported for the resulting content type are always rejected, even when bypass is enabled.
    """ # noqa: E501
    developer_tools_on_web_pages: Optional[AllowBlockControl] = Field(default=None, description="Control DevTools to avoid potential data leaks, inspecting page content, and running unauthorized code in the console.", alias="developerToolsOnWebPages")
    camera: Optional[AllowBlockControl] = Field(default=None, description="Control the ability to use camera in web pages.")
    microphone: Optional[AllowBlockControl] = Field(default=None, description="Control the ability to use microphone in web pages.")
    screenshot: Optional[ScreenshotControl] = None
    web_user_interaction: Optional[WebUserInteractionControl] = Field(default=None, alias="webUserInteraction")
    read_only_webpage: Optional[FormSubmissionControl] = Field(default=None, alias="readOnlyWebpage")
    live_page_scanning: Optional[LivePageScanningControl] = Field(default=None, alias="livePageScanning")
    webpage_watermarking: Optional[WatermarkControl] = Field(default=None, alias="webpageWatermarking")
    clipboard: Optional[ClipboardControl] = None
    typing_guard: Optional[SanitizingContentControl] = Field(default=None, alias="typingGuard")
    malicious_file_protection: Optional[MaliciousFileProtectionControl] = Field(default=None, alias="maliciousFileProtection")
    webpage_data_masking: Optional[WebpageDataMaskingControl] = Field(default=None, alias="webpageDataMasking")
    gen_ai_prompt: Optional[AllowBlockControl] = Field(default=None, alias="genAIPrompt")
    var_print: Optional[PrintControl] = Field(default=None, alias="print")
    dlp_profile_id: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Enterprise DLP (EDLP) data profile id (the same value returned by EDLP GET /v2/api/data-profiles). Write-only on POST/PATCH; reads return dlpProfile instead. Send null on PATCH to unlink the rule from any EDLP profile. ", alias="dlpProfileId")
    dlp_profile: Optional[DlpProfileRef] = Field(default=None, alias="dlpProfile")
    bypass_dlp_profile_validation: Optional[StrictBool] = Field(default=False, description="Bypass the content-agnostic data-profile compatibility check for controls in this object. When false (default), controls incompatible with the configured dlpProfileId are rejected with HTTP 400. When true, the rule saves and content-agnostic incompatible controls become runtime no-ops. Controls entirely unsupported for the resulting content type are always rejected, even when this is true. ", alias="bypassDlpProfileValidation")
    user_agent: Optional[UserAgentControl] = Field(default=None, alias="userAgent")
    custom_http_header: Optional[CustomHttpHeaderControl] = Field(default=None, alias="customHttpHeader")
    file_protection: Optional[FileProtectionControl] = Field(default=None, alias="fileProtection")
    __properties: ClassVar[List[str]] = ["developerToolsOnWebPages", "camera", "microphone", "screenshot", "webUserInteraction", "readOnlyWebpage", "livePageScanning", "webpageWatermarking", "clipboard", "typingGuard", "maliciousFileProtection", "webpageDataMasking", "genAIPrompt", "print", "dlpProfileId", "dlpProfile", "bypassDlpProfileValidation", "userAgent", "customHttpHeader", "fileProtection"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessAndDataDataControls from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of developer_tools_on_web_pages
        if self.developer_tools_on_web_pages:
            _dict['developerToolsOnWebPages'] = self.developer_tools_on_web_pages.to_dict()
        # override the default output from pydantic by calling `to_dict()` of camera
        if self.camera:
            _dict['camera'] = self.camera.to_dict()
        # override the default output from pydantic by calling `to_dict()` of microphone
        if self.microphone:
            _dict['microphone'] = self.microphone.to_dict()
        # override the default output from pydantic by calling `to_dict()` of screenshot
        if self.screenshot:
            _dict['screenshot'] = self.screenshot.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_user_interaction
        if self.web_user_interaction:
            _dict['webUserInteraction'] = self.web_user_interaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of read_only_webpage
        if self.read_only_webpage:
            _dict['readOnlyWebpage'] = self.read_only_webpage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of live_page_scanning
        if self.live_page_scanning:
            _dict['livePageScanning'] = self.live_page_scanning.to_dict()
        # override the default output from pydantic by calling `to_dict()` of webpage_watermarking
        if self.webpage_watermarking:
            _dict['webpageWatermarking'] = self.webpage_watermarking.to_dict()
        # override the default output from pydantic by calling `to_dict()` of clipboard
        if self.clipboard:
            _dict['clipboard'] = self.clipboard.to_dict()
        # override the default output from pydantic by calling `to_dict()` of typing_guard
        if self.typing_guard:
            _dict['typingGuard'] = self.typing_guard.to_dict()
        # override the default output from pydantic by calling `to_dict()` of malicious_file_protection
        if self.malicious_file_protection:
            _dict['maliciousFileProtection'] = self.malicious_file_protection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of webpage_data_masking
        if self.webpage_data_masking:
            _dict['webpageDataMasking'] = self.webpage_data_masking.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gen_ai_prompt
        if self.gen_ai_prompt:
            _dict['genAIPrompt'] = self.gen_ai_prompt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_print
        if self.var_print:
            _dict['print'] = self.var_print.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dlp_profile
        if self.dlp_profile:
            _dict['dlpProfile'] = self.dlp_profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_agent
        if self.user_agent:
            _dict['userAgent'] = self.user_agent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of custom_http_header
        if self.custom_http_header:
            _dict['customHttpHeader'] = self.custom_http_header.to_dict()
        # override the default output from pydantic by calling `to_dict()` of file_protection
        if self.file_protection:
            _dict['fileProtection'] = self.file_protection.to_dict()
        # set to None if developer_tools_on_web_pages (nullable) is None
        # and model_fields_set contains the field
        if self.developer_tools_on_web_pages is None and "developer_tools_on_web_pages" in self.model_fields_set:
            _dict['developerToolsOnWebPages'] = None

        # set to None if camera (nullable) is None
        # and model_fields_set contains the field
        if self.camera is None and "camera" in self.model_fields_set:
            _dict['camera'] = None

        # set to None if microphone (nullable) is None
        # and model_fields_set contains the field
        if self.microphone is None and "microphone" in self.model_fields_set:
            _dict['microphone'] = None

        # set to None if screenshot (nullable) is None
        # and model_fields_set contains the field
        if self.screenshot is None and "screenshot" in self.model_fields_set:
            _dict['screenshot'] = None

        # set to None if web_user_interaction (nullable) is None
        # and model_fields_set contains the field
        if self.web_user_interaction is None and "web_user_interaction" in self.model_fields_set:
            _dict['webUserInteraction'] = None

        # set to None if read_only_webpage (nullable) is None
        # and model_fields_set contains the field
        if self.read_only_webpage is None and "read_only_webpage" in self.model_fields_set:
            _dict['readOnlyWebpage'] = None

        # set to None if live_page_scanning (nullable) is None
        # and model_fields_set contains the field
        if self.live_page_scanning is None and "live_page_scanning" in self.model_fields_set:
            _dict['livePageScanning'] = None

        # set to None if webpage_watermarking (nullable) is None
        # and model_fields_set contains the field
        if self.webpage_watermarking is None and "webpage_watermarking" in self.model_fields_set:
            _dict['webpageWatermarking'] = None

        # set to None if clipboard (nullable) is None
        # and model_fields_set contains the field
        if self.clipboard is None and "clipboard" in self.model_fields_set:
            _dict['clipboard'] = None

        # set to None if typing_guard (nullable) is None
        # and model_fields_set contains the field
        if self.typing_guard is None and "typing_guard" in self.model_fields_set:
            _dict['typingGuard'] = None

        # set to None if malicious_file_protection (nullable) is None
        # and model_fields_set contains the field
        if self.malicious_file_protection is None and "malicious_file_protection" in self.model_fields_set:
            _dict['maliciousFileProtection'] = None

        # set to None if webpage_data_masking (nullable) is None
        # and model_fields_set contains the field
        if self.webpage_data_masking is None and "webpage_data_masking" in self.model_fields_set:
            _dict['webpageDataMasking'] = None

        # set to None if gen_ai_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.gen_ai_prompt is None and "gen_ai_prompt" in self.model_fields_set:
            _dict['genAIPrompt'] = None

        # set to None if var_print (nullable) is None
        # and model_fields_set contains the field
        if self.var_print is None and "var_print" in self.model_fields_set:
            _dict['print'] = None

        # set to None if dlp_profile_id (nullable) is None
        # and model_fields_set contains the field
        if self.dlp_profile_id is None and "dlp_profile_id" in self.model_fields_set:
            _dict['dlpProfileId'] = None

        # set to None if user_agent (nullable) is None
        # and model_fields_set contains the field
        if self.user_agent is None and "user_agent" in self.model_fields_set:
            _dict['userAgent'] = None

        # set to None if custom_http_header (nullable) is None
        # and model_fields_set contains the field
        if self.custom_http_header is None and "custom_http_header" in self.model_fields_set:
            _dict['customHttpHeader'] = None

        # set to None if file_protection (nullable) is None
        # and model_fields_set contains the field
        if self.file_protection is None and "file_protection" in self.model_fields_set:
            _dict['fileProtection'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessAndDataDataControls from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "developerToolsOnWebPages": AllowBlockControl.from_dict(obj["developerToolsOnWebPages"]) if obj.get("developerToolsOnWebPages") is not None else None,
            "camera": AllowBlockControl.from_dict(obj["camera"]) if obj.get("camera") is not None else None,
            "microphone": AllowBlockControl.from_dict(obj["microphone"]) if obj.get("microphone") is not None else None,
            "screenshot": ScreenshotControl.from_dict(obj["screenshot"]) if obj.get("screenshot") is not None else None,
            "webUserInteraction": WebUserInteractionControl.from_dict(obj["webUserInteraction"]) if obj.get("webUserInteraction") is not None else None,
            "readOnlyWebpage": FormSubmissionControl.from_dict(obj["readOnlyWebpage"]) if obj.get("readOnlyWebpage") is not None else None,
            "livePageScanning": LivePageScanningControl.from_dict(obj["livePageScanning"]) if obj.get("livePageScanning") is not None else None,
            "webpageWatermarking": WatermarkControl.from_dict(obj["webpageWatermarking"]) if obj.get("webpageWatermarking") is not None else None,
            "clipboard": ClipboardControl.from_dict(obj["clipboard"]) if obj.get("clipboard") is not None else None,
            "typingGuard": SanitizingContentControl.from_dict(obj["typingGuard"]) if obj.get("typingGuard") is not None else None,
            "maliciousFileProtection": MaliciousFileProtectionControl.from_dict(obj["maliciousFileProtection"]) if obj.get("maliciousFileProtection") is not None else None,
            "webpageDataMasking": WebpageDataMaskingControl.from_dict(obj["webpageDataMasking"]) if obj.get("webpageDataMasking") is not None else None,
            "genAIPrompt": AllowBlockControl.from_dict(obj["genAIPrompt"]) if obj.get("genAIPrompt") is not None else None,
            "print": PrintControl.from_dict(obj["print"]) if obj.get("print") is not None else None,
            "dlpProfileId": obj.get("dlpProfileId"),
            "dlpProfile": DlpProfileRef.from_dict(obj["dlpProfile"]) if obj.get("dlpProfile") is not None else None,
            "bypassDlpProfileValidation": obj.get("bypassDlpProfileValidation") if obj.get("bypassDlpProfileValidation") is not None else False,
            "userAgent": UserAgentControl.from_dict(obj["userAgent"]) if obj.get("userAgent") is not None else None,
            "customHttpHeader": CustomHttpHeaderControl.from_dict(obj["customHttpHeader"]) if obj.get("customHttpHeader") is not None else None,
            "fileProtection": FileProtectionControl.from_dict(obj["fileProtection"]) if obj.get("fileProtection") is not None else None
        })
        return _obj


