# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, Optional
from prisma_browser.models.access_input_action import AccessInputAction
from prisma_browser.models.access_input_address_bar_label import AccessInputAddressBarLabel
from prisma_browser.models.access_user_prompt import AccessUserPrompt
from prisma_browser.models.custom_dialog_text import CustomDialogText
from prisma_browser.models.custom_label import CustomLabel
from prisma_browser.models.open_in_prisma_browser import OpenInPrismaBrowser
from prisma_browser.models.override_duration_minutes import OverrideDurationMinutes
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccessInput(BaseModel):
    """
    Access control configuration for an access-and-data rule.  Note: on PATCH, the `access` block uses replace semantics — clients must re-send the full object on every update. Any field omitted is cleared (with the exception of internal fields not exposed by this API, such as `authMethod` and `enforceRedirect`, which are preserved from the existing rule). 
    """ # noqa: E501
    action: AccessInputAction
    user_prompt: Optional[AccessUserPrompt] = Field(default=None, alias="userPrompt")
    custom_dialog_text: Optional[CustomDialogText] = Field(default=None, alias="customDialogText")
    mfa_required: Optional[StrictBool] = Field(default=False, description="Whether the user must complete an MFA challenge before the control's restricted action is allowed. The MFA method (pinCode / identityProvider) is configured globally on the Browser Security Authentication Factor control and is not set per-rule.", alias="mfaRequired")
    authentication_duration_minutes: Optional[OverrideDurationMinutes] = Field(default=None, alias="authenticationDurationMinutes")
    open_in_prisma_browser: Optional[OpenInPrismaBrowser] = Field(default=None, alias="openInPrismaBrowser")
    address_bar_label: Optional[AccessInputAddressBarLabel] = Field(default=None, alias="addressBarLabel")
    custom_label: Optional[CustomLabel] = Field(default=None, alias="customLabel")
    __properties: ClassVar[List[str]] = ["action", "userPrompt", "customDialogText", "mfaRequired", "authenticationDurationMinutes", "openInPrismaBrowser", "addressBarLabel", "customLabel"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user_prompt
        if self.user_prompt:
            _dict['userPrompt'] = self.user_prompt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of custom_dialog_text
        if self.custom_dialog_text:
            _dict['customDialogText'] = self.custom_dialog_text.to_dict()
        # override the default output from pydantic by calling `to_dict()` of open_in_prisma_browser
        if self.open_in_prisma_browser:
            _dict['openInPrismaBrowser'] = self.open_in_prisma_browser.to_dict()
        # override the default output from pydantic by calling `to_dict()` of custom_label
        if self.custom_label:
            _dict['customLabel'] = self.custom_label.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "userPrompt": AccessUserPrompt.from_dict(obj["userPrompt"]) if obj.get("userPrompt") is not None else None,
            "customDialogText": CustomDialogText.from_dict(obj["customDialogText"]) if obj.get("customDialogText") is not None else None,
            "mfaRequired": obj.get("mfaRequired") if obj.get("mfaRequired") is not None else False,
            "authenticationDurationMinutes": obj.get("authenticationDurationMinutes"),
            "openInPrismaBrowser": OpenInPrismaBrowser.from_dict(obj["openInPrismaBrowser"]) if obj.get("openInPrismaBrowser") is not None else None,
            "addressBarLabel": obj.get("addressBarLabel"),
            "customLabel": CustomLabel.from_dict(obj["customLabel"]) if obj.get("customLabel") is not None else None
        })
        return _obj


