# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from prisma_browser.models.access_and_data_post_applications_application_groups import AccessAndDataPostApplicationsApplicationGroups
from prisma_browser.models.access_and_data_post_applications_local_desktop import AccessAndDataPostApplicationsLocalDesktop
from prisma_browser.models.access_and_data_post_applications_non_web import AccessAndDataPostApplicationsNonWeb
from prisma_browser.models.access_and_data_post_applications_private import AccessAndDataPostApplicationsPrivate
from prisma_browser.models.access_and_data_post_applications_saas import AccessAndDataPostApplicationsSaas
from prisma_browser.models.tenant_conditions import TenantConditions
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccessAndDataPostApplications(BaseModel):
    """
    Applications scope for creating an access-and-data rule, categorized by application type.
    """ # noqa: E501
    saas: Optional[AccessAndDataPostApplicationsSaas] = None
    private: Optional[AccessAndDataPostApplicationsPrivate] = None
    non_web: Optional[AccessAndDataPostApplicationsNonWeb] = Field(default=None, alias="nonWeb")
    local_desktop: Optional[AccessAndDataPostApplicationsLocalDesktop] = Field(default=None, alias="localDesktop")
    application_groups: Optional[AccessAndDataPostApplicationsApplicationGroups] = Field(default=None, alias="applicationGroups")
    tenant_conditions: Optional[TenantConditions] = Field(default=None, alias="tenantConditions")
    __properties: ClassVar[List[str]] = ["saas", "private", "nonWeb", "localDesktop", "applicationGroups", "tenantConditions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessAndDataPostApplications from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of saas
        if self.saas:
            _dict['saas'] = self.saas.to_dict()
        # override the default output from pydantic by calling `to_dict()` of private
        if self.private:
            _dict['private'] = self.private.to_dict()
        # override the default output from pydantic by calling `to_dict()` of non_web
        if self.non_web:
            _dict['nonWeb'] = self.non_web.to_dict()
        # override the default output from pydantic by calling `to_dict()` of local_desktop
        if self.local_desktop:
            _dict['localDesktop'] = self.local_desktop.to_dict()
        # override the default output from pydantic by calling `to_dict()` of application_groups
        if self.application_groups:
            _dict['applicationGroups'] = self.application_groups.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tenant_conditions
        if self.tenant_conditions:
            _dict['tenantConditions'] = self.tenant_conditions.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessAndDataPostApplications from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "saas": AccessAndDataPostApplicationsSaas.from_dict(obj["saas"]) if obj.get("saas") is not None else None,
            "private": AccessAndDataPostApplicationsPrivate.from_dict(obj["private"]) if obj.get("private") is not None else None,
            "nonWeb": AccessAndDataPostApplicationsNonWeb.from_dict(obj["nonWeb"]) if obj.get("nonWeb") is not None else None,
            "localDesktop": AccessAndDataPostApplicationsLocalDesktop.from_dict(obj["localDesktop"]) if obj.get("localDesktop") is not None else None,
            "applicationGroups": AccessAndDataPostApplicationsApplicationGroups.from_dict(obj["applicationGroups"]) if obj.get("applicationGroups") is not None else None,
            "tenantConditions": TenantConditions.from_dict(obj["tenantConditions"]) if obj.get("tenantConditions") is not None else None
        })
        return _obj


