# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import model_serializer, BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from prisma_browser.models.application_ref import ApplicationRef
from prisma_browser.models.web_classification import WebClassification
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccessAndDataApplicationsSaasSpecific(BaseModel):
    """
    Present when accessMode is specific
    """ # noqa: E501
    application_ids: Optional[List[ApplicationRef]] = Field(default=None, alias="applicationIds")
    urls: Optional[List[StrictStr]] = None
    web_classifications: Optional[Annotated[List[WebClassification], Field(min_length=1, max_length=100)]] = Field(default=None, description="Array of web classifications (URL categories) for content filtering", alias="webClassifications")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["applicationIds", "urls", "webClassifications"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    @model_serializer(mode="wrap")
    def _phantasos_drop_empty_additional_properties(self, handler) -> Any:
        """phantasos: omit an empty additional_properties bag from
        model_dump()/model_dump_json(); non-empty bags are left untouched.
        Respects exclude=/by_alias=/exclude_none=, so to_dict() is unchanged."""
        data = handler(self)
        if isinstance(data, dict) and data.get("additional_properties") == {}:
            data.pop("additional_properties")
        return data

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessAndDataApplicationsSaasSpecific from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in application_ids (list)
        _items = []
        if self.application_ids:
            for _item_application_ids in self.application_ids:
                if _item_application_ids:
                    _items.append(_item_application_ids.to_dict())
            _dict['applicationIds'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessAndDataApplicationsSaasSpecific from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "applicationIds": [ApplicationRef.from_dict(_item) for _item in obj["applicationIds"]] if obj.get("applicationIds") is not None else None,
            "urls": obj.get("urls"),
            "webClassifications": obj.get("webClassifications")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


