# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import model_serializer, BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from prisma_browser.models.custom_application_input import CustomApplicationInput
from prisma_browser.models.local_desktop_application_input import LocalDesktopApplicationInput
from prisma_browser.models.non_web_application_input import NonWebApplicationInput
from prisma_browser.models.private_application_input import PrivateApplicationInput
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CREATEORREPLACEAPPINPUT_ONE_OF_SCHEMAS = ["CustomApplicationInput", "LocalDesktopApplicationInput", "NonWebApplicationInput", "PrivateApplicationInput"]

class CreateOrReplaceAppInput(BaseModel):
    """
    CreateOrReplaceAppInput
    """
    # data type: CustomApplicationInput
    oneof_schema_1_validator: Optional[CustomApplicationInput] = None
    # data type: PrivateApplicationInput
    oneof_schema_2_validator: Optional[PrivateApplicationInput] = None
    # data type: NonWebApplicationInput
    oneof_schema_3_validator: Optional[NonWebApplicationInput] = None
    # data type: LocalDesktopApplicationInput
    oneof_schema_4_validator: Optional[LocalDesktopApplicationInput] = None
    actual_instance: Optional[Union[CustomApplicationInput, LocalDesktopApplicationInput, NonWebApplicationInput, PrivateApplicationInput]] = None
    one_of_schemas: Set[str] = { "CustomApplicationInput", "LocalDesktopApplicationInput", "NonWebApplicationInput", "PrivateApplicationInput" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = CreateOrReplaceAppInput.model_construct()
        error_messages = []
        match = 0
        # validate data type: CustomApplicationInput
        if not isinstance(v, CustomApplicationInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CustomApplicationInput`")
        else:
            match += 1
        # validate data type: PrivateApplicationInput
        if not isinstance(v, PrivateApplicationInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PrivateApplicationInput`")
        else:
            match += 1
        # validate data type: NonWebApplicationInput
        if not isinstance(v, NonWebApplicationInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NonWebApplicationInput`")
        else:
            match += 1
        # validate data type: LocalDesktopApplicationInput
        if not isinstance(v, LocalDesktopApplicationInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LocalDesktopApplicationInput`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in CreateOrReplaceAppInput with oneOf schemas: CustomApplicationInput, LocalDesktopApplicationInput, NonWebApplicationInput, PrivateApplicationInput. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in CreateOrReplaceAppInput with oneOf schemas: CustomApplicationInput, LocalDesktopApplicationInput, NonWebApplicationInput, PrivateApplicationInput. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("type")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `type` in the input.")

        # check if data type is `CustomApplicationInput`
        if _data_type == "custom":
            instance.actual_instance = CustomApplicationInput.from_json(json_str)
            return instance

        # check if data type is `LocalDesktopApplicationInput`
        if _data_type == "localdesktopcustom":
            instance.actual_instance = LocalDesktopApplicationInput.from_json(json_str)
            return instance

        # check if data type is `NonWebApplicationInput`
        if _data_type == "non-web":
            instance.actual_instance = NonWebApplicationInput.from_json(json_str)
            return instance

        # check if data type is `PrivateApplicationInput`
        if _data_type == "private":
            instance.actual_instance = PrivateApplicationInput.from_json(json_str)
            return instance

        # deserialize data into CustomApplicationInput
        try:
            instance.actual_instance = CustomApplicationInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PrivateApplicationInput
        try:
            instance.actual_instance = PrivateApplicationInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NonWebApplicationInput
        try:
            instance.actual_instance = NonWebApplicationInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LocalDesktopApplicationInput
        try:
            instance.actual_instance = LocalDesktopApplicationInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CreateOrReplaceAppInput with oneOf schemas: CustomApplicationInput, LocalDesktopApplicationInput, NonWebApplicationInput, PrivateApplicationInput. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CreateOrReplaceAppInput with oneOf schemas: CustomApplicationInput, LocalDesktopApplicationInput, NonWebApplicationInput, PrivateApplicationInput. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CustomApplicationInput, LocalDesktopApplicationInput, NonWebApplicationInput, PrivateApplicationInput]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    @model_serializer
    def _phantasos_unwrap(self) -> Any:
        """phantasos: serialize a oneOf wrapper as its actual instance, so
        model_dump()/model_dump_json() match the hand-written to_dict() instead
        of leaking the generator scaffolding (actual_instance, one_of_schemas, ...)."""
        return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


