# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import model_serializer, BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from prisma_browser.models.access_and_data_data_controls import AccessAndDataDataControls
from prisma_browser.models.access_and_data_login_controls_input import AccessAndDataLoginControlsInput
from prisma_browser.models.access_and_data_post_applications import AccessAndDataPostApplications
from prisma_browser.models.access_and_data_tracking import AccessAndDataTracking
from prisma_browser.models.access_input import AccessInput
from prisma_browser.models.post_scope import PostScope
from prisma_browser.models.rule_mode import RuleMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateAccessAndDataRuleRequest(BaseModel):
    """
    Request body for creating an Access and Data Policy rule.
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True, max_length=300)] = Field(description="The name or title of the rule.")
    description: Optional[Annotated[str, Field(strict=True, max_length=300)]] = Field(default=None, description="The detailed description of the rule.")
    scope: Optional[PostScope] = None
    mode: RuleMode
    applications: AccessAndDataPostApplications
    data_controls: Optional[AccessAndDataDataControls] = Field(default=None, alias="dataControls")
    access: AccessInput
    login_controls: Optional[AccessAndDataLoginControlsInput] = Field(default=None, alias="loginControls")
    tracking: AccessAndDataTracking
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "description", "scope", "mode", "applications", "dataControls", "access", "loginControls", "tracking"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"\S", value):
            raise ValueError(r"must validate the regular expression /\S/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    @model_serializer(mode="wrap")
    def _phantasos_drop_empty_additional_properties(self, handler) -> Any:
        """phantasos: omit an empty additional_properties bag from
        model_dump()/model_dump_json(); non-empty bags are left untouched.
        Respects exclude=/by_alias=/exclude_none=, so to_dict() is unchanged."""
        data = handler(self)
        if isinstance(data, dict) and data.get("additional_properties") == {}:
            data.pop("additional_properties")
        return data

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAccessAndDataRuleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of scope
        if self.scope:
            _dict['scope'] = self.scope.to_dict()
        # override the default output from pydantic by calling `to_dict()` of applications
        if self.applications:
            _dict['applications'] = self.applications.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data_controls
        if self.data_controls:
            _dict['dataControls'] = self.data_controls.to_dict()
        # override the default output from pydantic by calling `to_dict()` of access
        if self.access:
            _dict['access'] = self.access.to_dict()
        # override the default output from pydantic by calling `to_dict()` of login_controls
        if self.login_controls:
            _dict['loginControls'] = self.login_controls.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tracking
        if self.tracking:
            _dict['tracking'] = self.tracking.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAccessAndDataRuleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "scope": PostScope.from_dict(obj["scope"]) if obj.get("scope") is not None else None,
            "mode": obj.get("mode"),
            "applications": AccessAndDataPostApplications.from_dict(obj["applications"]) if obj.get("applications") is not None else None,
            "dataControls": AccessAndDataDataControls.from_dict(obj["dataControls"]) if obj.get("dataControls") is not None else None,
            "access": AccessInput.from_dict(obj["access"]) if obj.get("access") is not None else None,
            "loginControls": AccessAndDataLoginControlsInput.from_dict(obj["loginControls"]) if obj.get("loginControls") is not None else None,
            "tracking": AccessAndDataTracking.from_dict(obj["tracking"]) if obj.get("tracking") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


