# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from prisma_browser._lenient import LenientStrEnum, LenientIntEnum
from typing_extensions import Self


class DiskEncryptionVendorName(LenientStrEnum):
    """
    Disk encryption vendor name
    """

    """
    allowed enum values
    """
    ENUM_2BRIGHTSPARKS_PTE_LTD = '2BrightSparks Pte Ltd'
    ACRONIS = 'Acronis'
    ADOLIX = 'Adolix'
    APIMAC_COMMA__SOFTWARE = 'Apimac, software'
    APPLE_INC_DOT = 'Apple Inc.'
    ARCHICRYPT = 'archicrypt'
    ARCSERVE_LEFT_PARENTHESIS_USA_RIGHT_PARENTHESIS_COMMA__LLC = 'Arcserve (USA), LLC'
    ASHAMPOO_GMB_H_AMPERSAND__CO_DOT__KG = 'Ashampoo GmbH & Co. KG'
    AVG_TECHNOLOGIES_CZ_COMMA__S_DOT_R_DOT_O_DOT = 'AVG Technologies CZ, s.r.o.'
    AXANTUM_SOFTWARE_AB = 'Axantum Software AB'
    AXCRYPT_AB = 'AxCrypt AB'
    BEACHHEAD_SOLUTIONS = 'Beachhead Solutions'
    BECRYPT_LTD = 'Becrypt Ltd'
    BE_LIGHT_SOFTWARE_LTD_DOT = 'BeLight Software Ltd.'
    BITDEFENDER = 'Bitdefender'
    BRAINCELL_CONSULT_AMPERSAND__RESEARCH_GMB_H = 'Braincell consult & research GmbH'
    CHECK_POINT_SOFTWARE_TECHNOLOGIES = 'Check Point Software Technologies'
    CIPHERSHED = 'CipherShed'
    COMODO_SECURITY_SOLUTIONS = 'COMODO Security Solutions'
    CO_SO_SYS_LTD_DOT = 'CoSoSys Ltd.'
    CP_MINUS_LAB_DOT_COM = 'CP-Lab.com'
    CRYPTO_SYSTEMS_COMMA__INC_DOT = 'Crypto Systems, Inc.'
    CYPHERIX_SOFTWARE_PVT_DOT__LTD_DOT = 'Cypherix Software Pvt. Ltd.'
    DATEV_EG = 'DATEV eG'
    DEKART = 'Dekart'
    DELL_INC_DOT = 'Dell Inc.'
    DELTACRYPT_TECHNOLOGIES_INC = 'Deltacrypt Technologies Inc'
    DESLOCK_LIMITED = 'DESlock Limited'
    DIGITAL_MILLENIUM_INC_DOT = 'Digital Millenium Inc.'
    DOGOODSOFT = 'DoGoodSoft'
    EGOSECURE = 'EgoSecure'
    EGSOFTWEB = 'EGSoftWeb'
    ENC_SECURITY_SYSTEMS = 'ENC Security Systems'
    ENCRYPT4ALL_SOFTWARE = 'Encrypt4all Software'
    ESET = 'ESET'
    EVGENY_KOROVIN = 'Evgeny Korovin'
    EXLADE_COMMA__INC_DOT = 'EXLADE, Inc.'
    EXOSPHERE_LABS_COMMA__INC_DOT = 'Exosphere Labs, Inc.'
    FILE_ENCRYPTION_DOT_ORG_DOT = 'FileEncryption.org.'
    G_DATA_SOFTWARE_AG = 'G Data Software AG'
    GILISOFT_INTERNATIONAL_LLC = 'GiliSoft International LLC'
    GIT_HUB_COMMA__INC_DOT = 'GitHub, Inc.'
    GIT_LAB_INC_DOT = 'GitLab Inc.'
    HEWLETT_MINUS_PACKARD = 'Hewlett-Packard'
    HITEK_SOFTWARE_LLC = 'Hitek Software LLC'
    HUMMERSTUDIO = 'HummerStudio'
    IDRIX = 'IDRIX'
    INTERCRYPTO_LTD = 'InterCrypto Ltd'
    INV_SOFTWORKS_LLC = 'Inv Softworks LLC'
    JETICO_COMMA__INC_DOT = 'Jetico, Inc.'
    KASPERSKY_LAB = 'Kaspersky Lab'
    KOVELL_VENTURES_LTD_DOT = 'Kovell Ventures Ltd.'
    KROMTECH = 'Kromtech'
    KRUPTOS_2_SOFTWARE = 'Kruptos 2 Software'
    LAVASOFT = 'Lavasoft'
    MADOWSOFT_SOFTWARE = 'MadowSoft Software'
    MAX_SECURE_SOFTWARE = 'Max Secure Software'
    MC_AFEE_COMMA__INC_DOT = 'McAfee, Inc.'
    MICROSOFT_CORPORATION = 'Microsoft Corporation'
    MICRO_WORLD_TECHNOLOGIES_INC_DOT = 'MicroWorld Technologies Inc.'
    MNEMONIC_SECURITY_INC_DOT = 'Mnemonic Security Inc.'
    MO_RUN_DOT_NET = 'MoRUN.net'
    MSECURE_DATA_LABS = 'MSecure Data Labs'
    NCH_SOFTWARE = 'NCH Software'
    NEW_SOFTWARES_DOT_NET = 'New Softwares.net'
    NOMADESK_NV = 'Nomadesk NV'
    NTLDR = 'ntldr'
    PACKETIZER_COMMA__INC_DOT = 'Packetizer, Inc.'
    PANDA_SECURITY_COMMA__S_DOT_L_DOT = 'Panda Security, S.L.'
    PC_DYNAMICS = 'PC Dynamics'
    PDFKEY = 'PDFKey'
    PRIMX = 'PRIMX'
    R_MINUS_TOOLS_TECHNOLOGY_COMMA__INC_DOT = 'R-tools Technology, Inc.'
    RANQUEL_TECHNOLOGIES = 'Ranquel Technologies'
    RENTANADVISER = 'RentAnAdviser'
    ROGERS = 'Rogers'
    SAFETICA_TECHNOLOGIES = 'Safetica Technologies'
    SARAH_DEAN = 'Sarah Dean'
    SECURSTAR_GMBH = 'SecurStar GmbH'
    SOFTWINTER = 'SoftWinter'
    SOLID_PROGRAMS = 'Solid Programs'
    SOPHOS_LIMITED = 'Sophos Limited'
    STONEAGE_SOFTWARES = 'Stoneage Softwares'
    SUSE_LINUX_GMBH = 'SUSE LINUX GmbH'
    SYMANTEC_CORPORATION = 'Symantec Corporation'
    TEHTRIS = 'TEHTRIS'
    TESLINE_MINUS_SERVICE_SRL = 'Tesline-Service SRL'
    THE_GPG4WIN_PROJECT = 'The Gpg4win Project'
    TRELLIX = 'Trellix'
    TREND_MICRO_COMMA__INC_DOT = 'Trend Micro, Inc.'
    TRUECRYPT_FOUNDATION = 'TrueCrypt Foundation'
    TRUST_PORT_COMMA__A_DOT_S_DOT = 'TrustPort, a.s.'
    UTIMACO_SAFEWARE_AG = 'Utimaco Safeware AG'
    VASSIL_ARABADJIEV = 'Vassil Arabadjiev'
    WARDWIZ = 'WARDWIZ'
    WEBMINDS_COMMA__INC_DOT = 'Webminds, Inc.'
    WINENCRYPT = 'WinEncrypt'
    WIN_MAGIC_INC_DOT = 'WinMagic Inc.'
    ZMANDA_COMMA__INC_DOT = 'Zmanda, Inc.'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DiskEncryptionVendorName from a JSON string"""
        return cls(json.loads(json_str))


