# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from prisma_browser.models.file_type_filter_operator import FileTypeFilterOperator
from prisma_browser.models.file_type_filter_predefined_types_inner import FileTypeFilterPredefinedTypesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FileTypeFilter(BaseModel):
    """
    Filter by file type — categories, sub-categories, or specific extensions.
    """ # noqa: E501
    operator: FileTypeFilterOperator
    predefined_types: Optional[Annotated[List[FileTypeFilterPredefinedTypesInner], Field(max_length=12)]] = Field(default=None, description="Broad file-type buckets from the Prisma Browser catalog. Either a category (e.g., documents) or a sub-category (e.g., excel). Use this when the rule should match a whole group of files; for specific extensions, use customExtensions instead.", alias="predefinedTypes")
    custom_extensions: Optional[Annotated[List[Annotated[str, Field(strict=True, max_length=15)]], Field(max_length=50)]] = Field(default=None, description="Specific file extensions — both predefined extensions from the Prisma Browser catalog (e.g., pdf, docx) and your own proprietary or rare formats (e.g., xyz). All extensions live in this single array regardless of catalog membership.", alias="customExtensions")
    __properties: ClassVar[List[str]] = ["operator", "predefinedTypes", "customExtensions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileTypeFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileTypeFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operator": obj.get("operator"),
            "predefinedTypes": obj.get("predefinedTypes"),
            "customExtensions": obj.get("customExtensions")
        })
        return _obj


