# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from prisma_browser._lenient import LenientStrEnum, LenientIntEnum
from typing_extensions import Self


class FirewallVendorName(LenientStrEnum):
    """
    Firewall vendor name
    """

    """
    allowed enum values
    """
    AGNITUM_LTD_DOT = 'Agnitum Ltd.'
    NETGATE_TECHNOLOGIES_S_DOT_R_DOT_O_DOT = 'NETGATE Technologies s.r.o.'
    PARETO_LOGIC_COMMA__INC_DOT = 'ParetoLogic, Inc.'
    LANDESK_SOFTWARE_COMMA__INC_DOT = 'LANDESK Software, Inc.'
    AT_AMPERSAND_T = 'AT&T'
    BITDEFENDER = 'Bitdefender'
    MYSECURITYWIN = 'Mysecuritywin'
    G_DATA_SOFTWARE_AG = 'G Data Software AG'
    MAX_SECURE_SOFTWARE = 'Max Secure Software'
    AHN_LAB_COMMA__INC_DOT = 'AhnLab, Inc.'
    AVG_TECHNOLOGIES_CZ_COMMA__S_DOT_R_DOT_O_DOT = 'AVG Technologies CZ, s.r.o.'
    SYMANTEC_CORPORATION = 'Symantec Corporation'
    KASPERSKY_LAB = 'Kaspersky Lab'
    AVIRA_GMBH = 'Avira GmbH'
    PANDA_SECURITY_COMMA__S_DOT_L_DOT = 'Panda Security, S.L.'
    WEBROOT_SOFTWARE_COMMA__INC_DOT = 'Webroot Software, Inc.'
    QUICK_HEAL_TECHNOLOGIES_LEFT_PARENTHESIS_P_RIGHT_PARENTHESIS__LTD_DOT = 'Quick Heal Technologies (P) Ltd.'
    N_PROTECT_COMMA__INC_DOT = 'nProtect, Inc.'
    F_MINUS_SECURE_CORPORATION = 'F-Secure Corporation'
    THREAT_TRACK_SECURITY_COMMA__INC_DOT = 'ThreatTrack Security, Inc.'
    MC_AFEE_COMMA__INC_DOT = 'McAfee, Inc.'
    EEYE_DIGITAL_SECURITY = 'eEye Digital Security'
    ARCABIT = 'Arcabit'
    BEYOND_TRUST_COMMA__INC_DOT = 'BeyondTrust, Inc.'
    TELEFÓNICA_S_DOT_A_DOT = 'Telefónica S.A.'
    GEN_MINUS_X_TECHNOLOGIES = 'GEN-X Technologies'
    K7_COMPUTING_PVT_LTD = 'K7 Computing Pvt Ltd'
    FARONICS_CORPORATION = 'Faronics Corporation'
    TELUS = 'TELUS'
    KINGSOFT_CORPORATION = 'Kingsoft Corporation'
    BINI_SOFT_DOT_ORG = 'BiniSoft.org'
    GFI_SOFTWARE_LTD_DOT = 'GFI Software Ltd.'
    TG_SOFT_S_DOT_A_DOT_S_DOT = 'TG Soft S.a.s.'
    SCANDIUM_SECURITY_INC_DOT = 'Scandium Security Inc.'
    DATPOL = 'Datpol'
    TECH_GUARD_TECHNOLOGIES = 'Tech Guard Technologies'
    NCP_ENGINEERING_GMBH = 'NCP engineering GmbH'
    SOFTSPHERE_TECHNOLOGIES = 'SoftSphere Technologies'
    QUICK_GUARD_TECHNOLOGIES = 'Quick Guard Technologies'
    EMSISOFT_LTD = 'Emsisoft Ltd'
    DATALINK_INDUSTRIAL_CORPORATION = 'Datalink Industrial Corporation'
    COMODO_SECURITY_SOLUTIONS = 'COMODO Security Solutions'
    MICRO_WORLD_TECHNOLOGIES_INC_DOT = 'MicroWorld Technologies Inc.'
    AVAST_SOFTWARE_A_DOT_S_DOT = 'AVAST Software a.s.'
    ESET = 'ESET'
    BEIJING_RISING_INFORMATION_TECHNOLOGY_CO_DOT_COMMA__LTD_DOT = 'Beijing Rising Information Technology Co., Ltd.'
    SMART_HEAL = 'Smart Heal'
    ROGERS = 'Rogers'
    CHECK_POINT_SOFTWARE_TECHNOLOGIES = 'Check Point Software Technologies'
    CELLSECURITY = 'CellSecurity'
    AS3_SOFT4U = 'AS3 Soft4U'
    ATES_SOFTWARE_AMPERSAND__INTERNET_TECHNOLOGIES = 'Ates Software & Internet Technologies'
    MSECURE_DATA_LABS = 'MSecure Data Labs'
    SGA_SOLUTIONS = 'SGA SOLUTIONS'
    ALLIT_SERVICE_COMMA__LLC_DOT = 'ALLIT Service, LLC.'
    ADAWARE = 'adaware'
    SENTINELONE = 'SentinelOne'
    CROWD_STRIKE_COMMA__INC_DOT = 'CrowdStrike, Inc.'
    CSIS_SECURITY_GROUP = 'CSIS Security Group'
    SOURCENEXT_CORPORATION = 'SOURCENEXT CORPORATION'
    MICROSOFT_CORPORATION = 'Microsoft Corporation'
    SECUREMIX_LLC = 'SecureMix LLC'
    SWISS_SECURITY_LABORATORY_DOT = 'Swiss security laboratory.'
    ASIA_INFO_COMMA__INC_DOT = 'AsiaInfo, Inc.'
    INCA_INTERNET_CO_DOT_COMMA__LTD_DOT = 'INCA Internet Co., Ltd.'
    ES_TSOFT_CORP_DOT = 'ESTsoft Corp.'
    SUNRISE_ANTIVIRUS = 'Sunrise Antivirus'
    HAURI_COMMA__INC_DOT = 'Hauri, Inc.'
    SECURA_SHIELD_INDIA_PVT_DOT__LTD_DOT = 'SecuraShield India Pvt. Ltd.'
    NIFTY_CORPORATION = 'NIFTY Corporation'
    TREND_MICRO_COMMA__INC_DOT = 'Trend Micro, Inc.'
    FUJITSU_SERVICES_LTD_DOT = 'Fujitsu Services Ltd.'
    LOG_ME_IN_COMMA__INC_DOT = 'LogMeIn, Inc.'
    STORMSHIELD = 'Stormshield'
    PALO_ALTO_NETWORKS_COMMA__INC_DOT = 'Palo Alto Networks, Inc.'
    CHILI_SECURITY = 'Chili Security'
    SOPHOS_LIMITED = 'Sophos Limited'
    NORTONLIFELOCK_INC = 'NortonLifeLock Inc'
    MASSACHUSETTS_INSTITUTE_OF_TECHNOLOGY = 'Massachusetts Institute of Technology'
    WATCHGUARD_TECHNOLOGIES_INC = 'WatchGuard Technologies Inc'
    BEIJING_HUORONG_NETWORK_TECHNOLOGY_CO_DOT_COMMA__LTD_DOT = 'Beijing Huorong Network Technology Co., Ltd.'
    LE_MINH_THANH = 'Le Minh Thanh'
    QI_AN_XIN_GROUP = 'Qi An Xin Group'
    AVAST_SOFTWARE_S_DOT_R_DOT_O_DOT = 'Avast Software s.r.o.'
    TEHTRIS = 'TEHTRIS'
    AVIRA_OPERATIONS_GMB_H_AMPERSAND__CO_DOT__KG = 'Avira Operations GmbH & Co. KG'
    WITHSECURE_CORPORATION = 'WithSecure Corporation'
    MUSARUBRA_US_LLC_DOT = 'Musarubra US LLC.'
    GO_TO_COMMA__INC_DOT = 'GoTo, Inc.'
    INCA_INTERNET_CO_DOT_COMMA_LTD_DOT = 'INCA Internet Co.,Ltd.'
    SECURA_WEB_DATA_LABS_PVT_LTD = 'SECURA WEB DATA LABS PVT LTD'
    BROADCOM = 'Broadcom'
    GEN_DIGITAL_INC_DOT = 'Gen Digital Inc.'
    ACTIPACE_PRIVATE_LIMITED = 'Actipace Private Limited'
    SIYANO_LABS_PVT_DOT__LTD_DOT = 'Siyano Labs Pvt. Ltd.'
    BKAV_CORPORATION = 'Bkav Corporation'
    CMC_INFOSEC = 'CMC InfoSec'
    TOTAL_DEFENSE_COMMA__INC_DOT = 'Total Defense, Inc.'
    TRUST_PORT_COMMA__A_DOT_S_DOT = 'TrustPort, a.s.'
    FORTINET_INC_DOT = 'Fortinet Inc.'
    AVANQUEST_SOFTWARE = 'Avanquest Software'
    DOCTOR_WEB_COMMA__LTD_DOT = 'Doctor Web, Ltd.'
    SECURITY_SOFTWARE_LIMITED = 'Security Software Limited'
    BULL_GUARD_LTD_DOT = 'BullGuard Ltd.'
    HDD_LABS_DOT__INC = 'HDD Labs. Inc'
    EARTH_LINK_COMMA__INC_DOT = 'EarthLink, Inc.'
    ROBOSCAN_INC = 'Roboscan Inc'
    THIRTYSEVEN4 = 'Thirtyseven4'
    PC_SECURITY_SHIELD = 'PC Security Shield'
    CA_COMMA__INC_DOT = 'CA, Inc.'
    PRIVACYWARE_SLASH_PWI_COMMA__INC_DOT = 'Privacyware/PWI, Inc.'
    KÁROLY_PADOS = 'Károly Pados'
    PEER_BLOCK_COMMA__LLC = 'PeerBlock, LLC'
    PROGRAMMER_WORLD_DOT_NET = 'ProgrammerWorld.Net'
    JETICO_COMMA__INC_DOT = 'Jetico, Inc.'
    TINY_SOFTWARE_INC_DOT = 'Tiny Software Inc.'
    SPHINX_SOFTWARE = 'Sphinx Software'
    DEFENDER_PRO = 'Defender Pro'
    SOFT4EVER = 'Soft4Ever'
    LAVASOFT = 'Lavasoft'
    NORMAN_AS = 'Norman AS'
    PC_TOOLS_SOFTWARE = 'PC Tools Software'
    APPLE_INC_DOT = 'Apple Inc.'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FirewallVendorName from a JSON string"""
        return cls(json.loads(json_str))


