# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict
from prisma_browser.models.onboarding_wizard_control_steps_customize import OnboardingWizardControlStepsCustomize
from prisma_browser.models.onboarding_wizard_control_steps_extension import OnboardingWizardControlStepsExtension
from prisma_browser.models.onboarding_wizard_control_steps_import import OnboardingWizardControlStepsImport
from prisma_browser.models.onboarding_wizard_control_steps_mobile import OnboardingWizardControlStepsMobile
from prisma_browser.models.onboarding_wizard_control_steps_password_manager import OnboardingWizardControlStepsPasswordManager
from prisma_browser.models.onboarding_wizard_control_steps_policy import OnboardingWizardControlStepsPolicy
from prisma_browser.models.onboarding_wizard_control_steps_restriction import OnboardingWizardControlStepsRestriction
from prisma_browser.models.onboarding_wizard_control_steps_welcome import OnboardingWizardControlStepsWelcome
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OnboardingWizardControlSteps(BaseModel):
    """
    Onboarding wizard steps shown to end users. Required when enabled is true. Must not be set when enabled is false.
    """ # noqa: E501
    welcome: OnboardingWizardControlStepsWelcome
    customize: OnboardingWizardControlStepsCustomize
    var_import: OnboardingWizardControlStepsImport = Field(alias="import")
    policy: OnboardingWizardControlStepsPolicy
    extension: OnboardingWizardControlStepsExtension
    restriction: OnboardingWizardControlStepsRestriction
    mobile: OnboardingWizardControlStepsMobile
    password_manager: OnboardingWizardControlStepsPasswordManager = Field(alias="passwordManager")
    __properties: ClassVar[List[str]] = ["welcome", "customize", "import", "policy", "extension", "restriction", "mobile", "passwordManager"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OnboardingWizardControlSteps from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of welcome
        if self.welcome:
            _dict['welcome'] = self.welcome.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customize
        if self.customize:
            _dict['customize'] = self.customize.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_import
        if self.var_import:
            _dict['import'] = self.var_import.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of extension
        if self.extension:
            _dict['extension'] = self.extension.to_dict()
        # override the default output from pydantic by calling `to_dict()` of restriction
        if self.restriction:
            _dict['restriction'] = self.restriction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mobile
        if self.mobile:
            _dict['mobile'] = self.mobile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of password_manager
        if self.password_manager:
            _dict['passwordManager'] = self.password_manager.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OnboardingWizardControlSteps from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "welcome": OnboardingWizardControlStepsWelcome.from_dict(obj["welcome"]) if obj.get("welcome") is not None else None,
            "customize": OnboardingWizardControlStepsCustomize.from_dict(obj["customize"]) if obj.get("customize") is not None else None,
            "import": OnboardingWizardControlStepsImport.from_dict(obj["import"]) if obj.get("import") is not None else None,
            "policy": OnboardingWizardControlStepsPolicy.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "extension": OnboardingWizardControlStepsExtension.from_dict(obj["extension"]) if obj.get("extension") is not None else None,
            "restriction": OnboardingWizardControlStepsRestriction.from_dict(obj["restriction"]) if obj.get("restriction") is not None else None,
            "mobile": OnboardingWizardControlStepsMobile.from_dict(obj["mobile"]) if obj.get("mobile") is not None else None,
            "passwordManager": OnboardingWizardControlStepsPasswordManager.from_dict(obj["passwordManager"]) if obj.get("passwordManager") is not None else None
        })
        return _obj


