# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from prisma_browser._lenient import LenientStrEnum, LenientIntEnum
from typing_extensions import Self


class OverrideDurationMinutes(LenientStrEnum):
    """
    Duration in minutes (as a string) for a timeframe window (e.g. user-prompt bypass window or authentication session validity). Allowed values: 0 (single use / every time), 10 (10m), 60 (1h), 240 (4h), 540 (9h), 720 (12h), 1440 (24h), 4320 (3d), 10080 (7d), 20160 (14d), 43200 (30d), 86400 (60d), 129600 (90d).
    """

    """
    allowed enum values
    """
    ENUM_0 = '0'
    ENUM_10 = '10'
    ENUM_60 = '60'
    ENUM_240 = '240'
    ENUM_540 = '540'
    ENUM_720 = '720'
    ENUM_1440 = '1440'
    ENUM_4320 = '4320'
    ENUM_10080 = '10080'
    ENUM_20160 = '20160'
    ENUM_43200 = '43200'
    ENUM_86400 = '86400'
    ENUM_129600 = '129600'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OverrideDurationMinutes from a JSON string"""
        return cls(json.loads(json_str))


