# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from prisma_browser.models.post_scope_device_groups import PostScopeDeviceGroups
from prisma_browser.models.post_scope_locations import PostScopeLocations
from prisma_browser.models.post_scope_private_ips import PostScopePrivateIps
from prisma_browser.models.post_scope_public_ips import PostScopePublicIps
from prisma_browser.models.post_scope_users import PostScopeUsers
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PostScope(BaseModel):
    """
    Provide scope to describe this rule
    """ # noqa: E501
    users: Optional[PostScopeUsers] = None
    device_groups: Optional[PostScopeDeviceGroups] = Field(default=None, alias="deviceGroups")
    public_ips: Optional[PostScopePublicIps] = Field(default=None, alias="publicIps")
    private_ips: Optional[PostScopePrivateIps] = Field(default=None, alias="privateIps")
    locations: Optional[PostScopeLocations] = None
    __properties: ClassVar[List[str]] = ["users", "deviceGroups", "publicIps", "privateIps", "locations"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostScope from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of users
        if self.users:
            _dict['users'] = self.users.to_dict()
        # override the default output from pydantic by calling `to_dict()` of device_groups
        if self.device_groups:
            _dict['deviceGroups'] = self.device_groups.to_dict()
        # override the default output from pydantic by calling `to_dict()` of public_ips
        if self.public_ips:
            _dict['publicIps'] = self.public_ips.to_dict()
        # override the default output from pydantic by calling `to_dict()` of private_ips
        if self.private_ips:
            _dict['privateIps'] = self.private_ips.to_dict()
        # override the default output from pydantic by calling `to_dict()` of locations
        if self.locations:
            _dict['locations'] = self.locations.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostScope from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "users": PostScopeUsers.from_dict(obj["users"]) if obj.get("users") is not None else None,
            "deviceGroups": PostScopeDeviceGroups.from_dict(obj["deviceGroups"]) if obj.get("deviceGroups") is not None else None,
            "publicIps": PostScopePublicIps.from_dict(obj["publicIps"]) if obj.get("publicIps") is not None else None,
            "privateIps": PostScopePrivateIps.from_dict(obj["privateIps"]) if obj.get("privateIps") is not None else None,
            "locations": PostScopeLocations.from_dict(obj["locations"]) if obj.get("locations") is not None else None
        })
        return _obj


