# coding: utf-8

"""
    Prisma Browser Management Console Public API

    This Open API spec file represents the APIs available for Palo Alto Networks Prisma Browser Management APIs. These APIs are available for all Prisma Browser tenants to scale and automate their processes related to the browser. All of the functionality exposed by these APIs can also be performed using the Prisma Browser User Interface. These APIs use the common SASE authentication mechanism and base URL. See the Prisma SASE API Get Started guide for more information. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at https://www.paloaltonetworks.com/company/trademarks.html. All other marks mentioned herein may be trademarks of their respective companies.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from prisma_browser.models.allow_block_control import AllowBlockControl
from prisma_browser.models.allowed_or_blocked_extensions_control import AllowedOrBlockedExtensionsControl
from prisma_browser.models.allowed_printers_control import AllowedPrintersControl
from prisma_browser.models.authentication_factor_control import AuthenticationFactorControl
from prisma_browser.models.authentication_server_allowlist_control import AuthenticationServerAllowlistControl
from prisma_browser.models.block_extensions_by_permissions_control import BlockExtensionsByPermissionsControl
from prisma_browser.models.browser_history_control import BrowserHistoryControl
from prisma_browser.models.browser_lock_control import BrowserLockControl
from prisma_browser.models.browser_self_protection_control import BrowserSelfProtectionControl
from prisma_browser.models.concurrent_number_of_devices_control import ConcurrentNumberOfDevicesControl
from prisma_browser.models.cookies_control import CookiesControl
from prisma_browser.models.dns_over_https_control import DnsOverHttpsControl
from prisma_browser.models.enable_disable_control import EnableDisableControl
from prisma_browser.models.enhanced_tracking_protection_control import EnhancedTrackingProtectionControl
from prisma_browser.models.flush_browser_data_control import FlushBrowserDataControl
from prisma_browser.models.force_https_control import ForceHttpsControl
from prisma_browser.models.internet_explorer_compatibility_mode_control import InternetExplorerCompatibilityModeControl
from prisma_browser.models.java_script_v8_jit_and_web_assembly_control import JavaScriptV8JitAndWebAssemblyControl
from prisma_browser.models.kerberos_delegation_allowlist_control import KerberosDelegationAllowlistControl
from prisma_browser.models.keylogging_protection_control import KeyloggingProtectionControl
from prisma_browser.models.launching_external_applications_control import LaunchingExternalApplicationsControl
from prisma_browser.models.legacy_password_manager_control import LegacyPasswordManagerControl
from prisma_browser.models.local_network_access_restrictions_control import LocalNetworkAccessRestrictionsControl
from prisma_browser.models.native_messaging_hosts_control import NativeMessagingHostsControl
from prisma_browser.models.notifications_control import NotificationsControl
from prisma_browser.models.open_links_in_external_apps_control import OpenLinksInExternalAppsControl
from prisma_browser.models.pages_with_insecure_content_control import PagesWithInsecureContentControl
from prisma_browser.models.popups_control import PopupsControl
from prisma_browser.models.post_quantum_key_security_control import PostQuantumKeySecurityControl
from prisma_browser.models.restrict_extension_host_permissions_control import RestrictExtensionHostPermissionsControl
from prisma_browser.models.session_refresh_control import SessionRefreshControl
from prisma_browser.models.trusted_certificate_authorities_control import TrustedCertificateAuthoritiesControl
from prisma_browser.models.web_rtc_control import WebRtcControl
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SecurityControls(BaseModel):
    """
    Controls for security rules.
    """ # noqa: E501
    developer_tools_for_extensions: Optional[AllowBlockControl] = Field(default=None, description="Control DevTools to avoid inspection of browser extensions.", alias="developerToolsForExtensions")
    cast: Optional[AllowBlockControl] = Field(default=None, description="Control the ability to cast a tab or the whole desktop via Prisma Browser. Prisma Browser restart required to apply.")
    cookies_protection: Optional[EnableDisableControl] = Field(default=None, description="Control the encryption of stored cookies on the device.", alias="cookiesProtection")
    browser_history: Optional[BrowserHistoryControl] = Field(default=None, alias="browserHistory")
    dns_over_https: Optional[DnsOverHttpsControl] = Field(default=None, alias="dnsOverHttps")
    browser_self_protection: Optional[BrowserSelfProtectionControl] = Field(default=None, alias="browserSelfProtection")
    keylogging_protection: Optional[KeyloggingProtectionControl] = Field(default=None, alias="keyloggingProtection")
    browser_lock: Optional[BrowserLockControl] = Field(default=None, alias="browserLock")
    authentication_factor: Optional[AuthenticationFactorControl] = Field(default=None, alias="authenticationFactor")
    session_refresh: Optional[SessionRefreshControl] = Field(default=None, alias="sessionRefresh")
    native_messaging_hosts: Optional[NativeMessagingHostsControl] = Field(default=None, alias="nativeMessagingHosts")
    allowed_or_blocked_extensions: Optional[AllowedOrBlockedExtensionsControl] = Field(default=None, alias="allowedOrBlockedExtensions")
    block_extensions_by_permissions: Optional[BlockExtensionsByPermissionsControl] = Field(default=None, alias="blockExtensionsByPermissions")
    post_quantum_key_security: Optional[PostQuantumKeySecurityControl] = Field(default=None, alias="postQuantumKeySecurity")
    strict_origin_isolation: Optional[EnableDisableControl] = Field(default=None, description="Isolates every origin in its own agent-cluster, preventing scripts on one sub-domain from interacting with another.", alias="strictOriginIsolation")
    advanced_browser_protection: Optional[EnableDisableControl] = Field(default=None, description="Stops zero-day WebAssembly attacks in real time by monitoring in-browser memory behavior and terminating malicious execution before any impact occurs.", alias="advancedBrowserProtection")
    user_data_directory_protection: Optional[EnableDisableControl] = Field(default=None, description="Enforce hardware based detections to prevent data directory and browser session theft.", alias="userDataDirectoryProtection")
    mobile_password_saving: Optional[AllowBlockControl] = Field(default=None, description="Control passwords saving in the mobile browser.", alias="mobilePasswordSaving")
    autofill_of_forms: Optional[AllowBlockControl] = Field(default=None, description="Control saving forms data in the browser.", alias="autofillOfForms")
    autofill_of_credit_cards: Optional[AllowBlockControl] = Field(default=None, description="Control saving credit cards in the browser.", alias="autofillOfCreditCards")
    java_script_running_from_omnibox: Optional[AllowBlockControl] = Field(default=None, description="Control the ability to execute JavaScript code from the browser omnibox.", alias="javaScriptRunningFromOmnibox")
    pages_with_ssl_errors: Optional[AllowBlockControl] = Field(default=None, description="Block \"Proceed to [FQDN] (unsafe)\" option when getting an SSL error. Such errors might appear during SSL MitM attack.", alias="pagesWithSslErrors")
    basic_authentication_over_http: Optional[AllowBlockControl] = Field(default=None, description="Set whether basic authentication can be used over HTTP websites.", alias="basicAuthenticationOverHttp")
    third_party_cookies: Optional[AllowBlockControl] = Field(default=None, description="Set whether elements in the web page that aren't from the domain that's in the browser's address bar can set cookies.", alias="thirdPartyCookies")
    print_preview: Optional[AllowBlockControl] = Field(default=None, description="Control the preview in the printing window, which might be exploited.", alias="printPreview")
    google_cloud_print: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the Google Cloud Print, which might be exploited.", alias="googleCloudPrint")
    allowed_printers: Optional[AllowedPrintersControl] = Field(default=None, alias="allowedPrinters")
    open_links_in_external_apps: Optional[OpenLinksInExternalAppsControl] = Field(default=None, alias="openLinksInExternalApps")
    trusted_certificate_authorities: Optional[TrustedCertificateAuthoritiesControl] = Field(default=None, alias="trustedCertificateAuthorities")
    remote_host_firewall_traversal: Optional[AllowBlockControl] = Field(default=None, description="Manage whether Remote Desktop may connect from outside the LAN or VPN by traversing firewalls.", alias="remoteHostFirewallTraversal")
    end_process_via_task_manager: Optional[AllowBlockControl] = Field(default=None, description="Choose whether end users can end browser processes via the browser task manager.", alias="endProcessViaTaskManager")
    pdfium: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the PDFium library to render PDF pages, which might be exploited. When PDFium is disabled, encrypted PDF files won't be loaded in Prisma Browser.")
    web_gl_api: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the WebGL library, which might be exploited.", alias="webGlApi")
    file_system_api: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the File System API, which might be exploited.", alias="fileSystemApi")
    sensors_api: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the Sensor API, which might be exploited.", alias="sensorsApi")
    web_serial_api: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the WebSerial API, which might be exploited.", alias="webSerialApi")
    web_bluetooth_api: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the WebBluetooth API, which might be exploited.", alias="webBluetoothApi")
    web_usb_api: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the WebUSB API, which might be exploited.", alias="webUsbApi")
    web_hid_api: Optional[AllowBlockControl] = Field(default=None, description="Control the availability of the WebHID API, which might be exploited.", alias="webHidApi")
    quic_protocol: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the QUIC protocol, which might be exploited.", alias="quicProtocol")
    web_clipboard_api: Optional[AllowBlockControl] = Field(default=None, description="Control the use of the Clipboard API, which might be exploited.", alias="webClipboardApi")
    local_fonts: Optional[AllowBlockControl] = Field(default=None, description="Control the access to local fonts installed on the device, which might be exploited.", alias="localFonts")
    flush_browser_data: Optional[FlushBrowserDataControl] = Field(default=None, alias="flushBrowserData")
    legacy_password_manager: Optional[LegacyPasswordManagerControl] = Field(default=None, alias="legacyPasswordManager")
    hide_sensitive_data_from_extensions: Optional[EnableDisableControl] = Field(default=None, description="Prevent all extensions from accessing cookies and authorization data sent by the browser.", alias="hideSensitiveDataFromExtensions")
    internet_explorer_compatibility_mode: Optional[InternetExplorerCompatibilityModeControl] = Field(default=None, alias="internetExplorerCompatibilityMode")
    launching_external_applications: Optional[LaunchingExternalApplicationsControl] = Field(default=None, alias="launchingExternalApplications")
    cookies: Optional[CookiesControl] = None
    local_network_access_restrictions: Optional[LocalNetworkAccessRestrictionsControl] = Field(default=None, alias="localNetworkAccessRestrictions")
    enhanced_tracking_protection: Optional[EnhancedTrackingProtectionControl] = Field(default=None, alias="enhancedTrackingProtection")
    force_https: Optional[ForceHttpsControl] = Field(default=None, alias="forceHttps")
    java_script_v8_jit_and_web_assembly: Optional[JavaScriptV8JitAndWebAssemblyControl] = Field(default=None, alias="javaScriptV8JitAndWebAssembly")
    restrict_extension_host_permissions: Optional[RestrictExtensionHostPermissionsControl] = Field(default=None, alias="restrictExtensionHostPermissions")
    web_rtc: Optional[WebRtcControl] = Field(default=None, alias="webRtc")
    notifications: Optional[NotificationsControl] = None
    popups: Optional[PopupsControl] = None
    pages_with_insecure_content: Optional[PagesWithInsecureContentControl] = Field(default=None, alias="pagesWithInsecureContent")
    kerberos_delegation_allowlist: Optional[KerberosDelegationAllowlistControl] = Field(default=None, alias="kerberosDelegationAllowlist")
    authentication_server_allowlist: Optional[AuthenticationServerAllowlistControl] = Field(default=None, alias="authenticationServerAllowlist")
    concurrent_number_of_devices: Optional[ConcurrentNumberOfDevicesControl] = Field(default=None, alias="concurrentNumberOfDevices")
    __properties: ClassVar[List[str]] = ["developerToolsForExtensions", "cast", "cookiesProtection", "browserHistory", "dnsOverHttps", "browserSelfProtection", "keyloggingProtection", "browserLock", "authenticationFactor", "sessionRefresh", "nativeMessagingHosts", "allowedOrBlockedExtensions", "blockExtensionsByPermissions", "postQuantumKeySecurity", "strictOriginIsolation", "advancedBrowserProtection", "userDataDirectoryProtection", "mobilePasswordSaving", "autofillOfForms", "autofillOfCreditCards", "javaScriptRunningFromOmnibox", "pagesWithSslErrors", "basicAuthenticationOverHttp", "thirdPartyCookies", "printPreview", "googleCloudPrint", "allowedPrinters", "openLinksInExternalApps", "trustedCertificateAuthorities", "remoteHostFirewallTraversal", "endProcessViaTaskManager", "pdfium", "webGlApi", "fileSystemApi", "sensorsApi", "webSerialApi", "webBluetoothApi", "webUsbApi", "webHidApi", "quicProtocol", "webClipboardApi", "localFonts", "flushBrowserData", "legacyPasswordManager", "hideSensitiveDataFromExtensions", "internetExplorerCompatibilityMode", "launchingExternalApplications", "cookies", "localNetworkAccessRestrictions", "enhancedTrackingProtection", "forceHttps", "javaScriptV8JitAndWebAssembly", "restrictExtensionHostPermissions", "webRtc", "notifications", "popups", "pagesWithInsecureContent", "kerberosDelegationAllowlist", "authenticationServerAllowlist", "concurrentNumberOfDevices"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecurityControls from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of developer_tools_for_extensions
        if self.developer_tools_for_extensions:
            _dict['developerToolsForExtensions'] = self.developer_tools_for_extensions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cast
        if self.cast:
            _dict['cast'] = self.cast.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cookies_protection
        if self.cookies_protection:
            _dict['cookiesProtection'] = self.cookies_protection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of browser_history
        if self.browser_history:
            _dict['browserHistory'] = self.browser_history.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dns_over_https
        if self.dns_over_https:
            _dict['dnsOverHttps'] = self.dns_over_https.to_dict()
        # override the default output from pydantic by calling `to_dict()` of browser_self_protection
        if self.browser_self_protection:
            _dict['browserSelfProtection'] = self.browser_self_protection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of keylogging_protection
        if self.keylogging_protection:
            _dict['keyloggingProtection'] = self.keylogging_protection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of browser_lock
        if self.browser_lock:
            _dict['browserLock'] = self.browser_lock.to_dict()
        # override the default output from pydantic by calling `to_dict()` of authentication_factor
        if self.authentication_factor:
            _dict['authenticationFactor'] = self.authentication_factor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of session_refresh
        if self.session_refresh:
            _dict['sessionRefresh'] = self.session_refresh.to_dict()
        # override the default output from pydantic by calling `to_dict()` of native_messaging_hosts
        if self.native_messaging_hosts:
            _dict['nativeMessagingHosts'] = self.native_messaging_hosts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of allowed_or_blocked_extensions
        if self.allowed_or_blocked_extensions:
            _dict['allowedOrBlockedExtensions'] = self.allowed_or_blocked_extensions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of block_extensions_by_permissions
        if self.block_extensions_by_permissions:
            _dict['blockExtensionsByPermissions'] = self.block_extensions_by_permissions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of post_quantum_key_security
        if self.post_quantum_key_security:
            _dict['postQuantumKeySecurity'] = self.post_quantum_key_security.to_dict()
        # override the default output from pydantic by calling `to_dict()` of strict_origin_isolation
        if self.strict_origin_isolation:
            _dict['strictOriginIsolation'] = self.strict_origin_isolation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of advanced_browser_protection
        if self.advanced_browser_protection:
            _dict['advancedBrowserProtection'] = self.advanced_browser_protection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_data_directory_protection
        if self.user_data_directory_protection:
            _dict['userDataDirectoryProtection'] = self.user_data_directory_protection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mobile_password_saving
        if self.mobile_password_saving:
            _dict['mobilePasswordSaving'] = self.mobile_password_saving.to_dict()
        # override the default output from pydantic by calling `to_dict()` of autofill_of_forms
        if self.autofill_of_forms:
            _dict['autofillOfForms'] = self.autofill_of_forms.to_dict()
        # override the default output from pydantic by calling `to_dict()` of autofill_of_credit_cards
        if self.autofill_of_credit_cards:
            _dict['autofillOfCreditCards'] = self.autofill_of_credit_cards.to_dict()
        # override the default output from pydantic by calling `to_dict()` of java_script_running_from_omnibox
        if self.java_script_running_from_omnibox:
            _dict['javaScriptRunningFromOmnibox'] = self.java_script_running_from_omnibox.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pages_with_ssl_errors
        if self.pages_with_ssl_errors:
            _dict['pagesWithSslErrors'] = self.pages_with_ssl_errors.to_dict()
        # override the default output from pydantic by calling `to_dict()` of basic_authentication_over_http
        if self.basic_authentication_over_http:
            _dict['basicAuthenticationOverHttp'] = self.basic_authentication_over_http.to_dict()
        # override the default output from pydantic by calling `to_dict()` of third_party_cookies
        if self.third_party_cookies:
            _dict['thirdPartyCookies'] = self.third_party_cookies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of print_preview
        if self.print_preview:
            _dict['printPreview'] = self.print_preview.to_dict()
        # override the default output from pydantic by calling `to_dict()` of google_cloud_print
        if self.google_cloud_print:
            _dict['googleCloudPrint'] = self.google_cloud_print.to_dict()
        # override the default output from pydantic by calling `to_dict()` of allowed_printers
        if self.allowed_printers:
            _dict['allowedPrinters'] = self.allowed_printers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of open_links_in_external_apps
        if self.open_links_in_external_apps:
            _dict['openLinksInExternalApps'] = self.open_links_in_external_apps.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trusted_certificate_authorities
        if self.trusted_certificate_authorities:
            _dict['trustedCertificateAuthorities'] = self.trusted_certificate_authorities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of remote_host_firewall_traversal
        if self.remote_host_firewall_traversal:
            _dict['remoteHostFirewallTraversal'] = self.remote_host_firewall_traversal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of end_process_via_task_manager
        if self.end_process_via_task_manager:
            _dict['endProcessViaTaskManager'] = self.end_process_via_task_manager.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pdfium
        if self.pdfium:
            _dict['pdfium'] = self.pdfium.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_gl_api
        if self.web_gl_api:
            _dict['webGlApi'] = self.web_gl_api.to_dict()
        # override the default output from pydantic by calling `to_dict()` of file_system_api
        if self.file_system_api:
            _dict['fileSystemApi'] = self.file_system_api.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sensors_api
        if self.sensors_api:
            _dict['sensorsApi'] = self.sensors_api.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_serial_api
        if self.web_serial_api:
            _dict['webSerialApi'] = self.web_serial_api.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_bluetooth_api
        if self.web_bluetooth_api:
            _dict['webBluetoothApi'] = self.web_bluetooth_api.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_usb_api
        if self.web_usb_api:
            _dict['webUsbApi'] = self.web_usb_api.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_hid_api
        if self.web_hid_api:
            _dict['webHidApi'] = self.web_hid_api.to_dict()
        # override the default output from pydantic by calling `to_dict()` of quic_protocol
        if self.quic_protocol:
            _dict['quicProtocol'] = self.quic_protocol.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_clipboard_api
        if self.web_clipboard_api:
            _dict['webClipboardApi'] = self.web_clipboard_api.to_dict()
        # override the default output from pydantic by calling `to_dict()` of local_fonts
        if self.local_fonts:
            _dict['localFonts'] = self.local_fonts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of flush_browser_data
        if self.flush_browser_data:
            _dict['flushBrowserData'] = self.flush_browser_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of legacy_password_manager
        if self.legacy_password_manager:
            _dict['legacyPasswordManager'] = self.legacy_password_manager.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hide_sensitive_data_from_extensions
        if self.hide_sensitive_data_from_extensions:
            _dict['hideSensitiveDataFromExtensions'] = self.hide_sensitive_data_from_extensions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of internet_explorer_compatibility_mode
        if self.internet_explorer_compatibility_mode:
            _dict['internetExplorerCompatibilityMode'] = self.internet_explorer_compatibility_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of launching_external_applications
        if self.launching_external_applications:
            _dict['launchingExternalApplications'] = self.launching_external_applications.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cookies
        if self.cookies:
            _dict['cookies'] = self.cookies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of local_network_access_restrictions
        if self.local_network_access_restrictions:
            _dict['localNetworkAccessRestrictions'] = self.local_network_access_restrictions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of enhanced_tracking_protection
        if self.enhanced_tracking_protection:
            _dict['enhancedTrackingProtection'] = self.enhanced_tracking_protection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of force_https
        if self.force_https:
            _dict['forceHttps'] = self.force_https.to_dict()
        # override the default output from pydantic by calling `to_dict()` of java_script_v8_jit_and_web_assembly
        if self.java_script_v8_jit_and_web_assembly:
            _dict['javaScriptV8JitAndWebAssembly'] = self.java_script_v8_jit_and_web_assembly.to_dict()
        # override the default output from pydantic by calling `to_dict()` of restrict_extension_host_permissions
        if self.restrict_extension_host_permissions:
            _dict['restrictExtensionHostPermissions'] = self.restrict_extension_host_permissions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_rtc
        if self.web_rtc:
            _dict['webRtc'] = self.web_rtc.to_dict()
        # override the default output from pydantic by calling `to_dict()` of notifications
        if self.notifications:
            _dict['notifications'] = self.notifications.to_dict()
        # override the default output from pydantic by calling `to_dict()` of popups
        if self.popups:
            _dict['popups'] = self.popups.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pages_with_insecure_content
        if self.pages_with_insecure_content:
            _dict['pagesWithInsecureContent'] = self.pages_with_insecure_content.to_dict()
        # override the default output from pydantic by calling `to_dict()` of kerberos_delegation_allowlist
        if self.kerberos_delegation_allowlist:
            _dict['kerberosDelegationAllowlist'] = self.kerberos_delegation_allowlist.to_dict()
        # override the default output from pydantic by calling `to_dict()` of authentication_server_allowlist
        if self.authentication_server_allowlist:
            _dict['authenticationServerAllowlist'] = self.authentication_server_allowlist.to_dict()
        # override the default output from pydantic by calling `to_dict()` of concurrent_number_of_devices
        if self.concurrent_number_of_devices:
            _dict['concurrentNumberOfDevices'] = self.concurrent_number_of_devices.to_dict()
        # set to None if developer_tools_for_extensions (nullable) is None
        # and model_fields_set contains the field
        if self.developer_tools_for_extensions is None and "developer_tools_for_extensions" in self.model_fields_set:
            _dict['developerToolsForExtensions'] = None

        # set to None if cast (nullable) is None
        # and model_fields_set contains the field
        if self.cast is None and "cast" in self.model_fields_set:
            _dict['cast'] = None

        # set to None if cookies_protection (nullable) is None
        # and model_fields_set contains the field
        if self.cookies_protection is None and "cookies_protection" in self.model_fields_set:
            _dict['cookiesProtection'] = None

        # set to None if browser_history (nullable) is None
        # and model_fields_set contains the field
        if self.browser_history is None and "browser_history" in self.model_fields_set:
            _dict['browserHistory'] = None

        # set to None if dns_over_https (nullable) is None
        # and model_fields_set contains the field
        if self.dns_over_https is None and "dns_over_https" in self.model_fields_set:
            _dict['dnsOverHttps'] = None

        # set to None if browser_self_protection (nullable) is None
        # and model_fields_set contains the field
        if self.browser_self_protection is None and "browser_self_protection" in self.model_fields_set:
            _dict['browserSelfProtection'] = None

        # set to None if keylogging_protection (nullable) is None
        # and model_fields_set contains the field
        if self.keylogging_protection is None and "keylogging_protection" in self.model_fields_set:
            _dict['keyloggingProtection'] = None

        # set to None if browser_lock (nullable) is None
        # and model_fields_set contains the field
        if self.browser_lock is None and "browser_lock" in self.model_fields_set:
            _dict['browserLock'] = None

        # set to None if authentication_factor (nullable) is None
        # and model_fields_set contains the field
        if self.authentication_factor is None and "authentication_factor" in self.model_fields_set:
            _dict['authenticationFactor'] = None

        # set to None if session_refresh (nullable) is None
        # and model_fields_set contains the field
        if self.session_refresh is None and "session_refresh" in self.model_fields_set:
            _dict['sessionRefresh'] = None

        # set to None if native_messaging_hosts (nullable) is None
        # and model_fields_set contains the field
        if self.native_messaging_hosts is None and "native_messaging_hosts" in self.model_fields_set:
            _dict['nativeMessagingHosts'] = None

        # set to None if allowed_or_blocked_extensions (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_or_blocked_extensions is None and "allowed_or_blocked_extensions" in self.model_fields_set:
            _dict['allowedOrBlockedExtensions'] = None

        # set to None if block_extensions_by_permissions (nullable) is None
        # and model_fields_set contains the field
        if self.block_extensions_by_permissions is None and "block_extensions_by_permissions" in self.model_fields_set:
            _dict['blockExtensionsByPermissions'] = None

        # set to None if post_quantum_key_security (nullable) is None
        # and model_fields_set contains the field
        if self.post_quantum_key_security is None and "post_quantum_key_security" in self.model_fields_set:
            _dict['postQuantumKeySecurity'] = None

        # set to None if strict_origin_isolation (nullable) is None
        # and model_fields_set contains the field
        if self.strict_origin_isolation is None and "strict_origin_isolation" in self.model_fields_set:
            _dict['strictOriginIsolation'] = None

        # set to None if advanced_browser_protection (nullable) is None
        # and model_fields_set contains the field
        if self.advanced_browser_protection is None and "advanced_browser_protection" in self.model_fields_set:
            _dict['advancedBrowserProtection'] = None

        # set to None if user_data_directory_protection (nullable) is None
        # and model_fields_set contains the field
        if self.user_data_directory_protection is None and "user_data_directory_protection" in self.model_fields_set:
            _dict['userDataDirectoryProtection'] = None

        # set to None if mobile_password_saving (nullable) is None
        # and model_fields_set contains the field
        if self.mobile_password_saving is None and "mobile_password_saving" in self.model_fields_set:
            _dict['mobilePasswordSaving'] = None

        # set to None if autofill_of_forms (nullable) is None
        # and model_fields_set contains the field
        if self.autofill_of_forms is None and "autofill_of_forms" in self.model_fields_set:
            _dict['autofillOfForms'] = None

        # set to None if autofill_of_credit_cards (nullable) is None
        # and model_fields_set contains the field
        if self.autofill_of_credit_cards is None and "autofill_of_credit_cards" in self.model_fields_set:
            _dict['autofillOfCreditCards'] = None

        # set to None if java_script_running_from_omnibox (nullable) is None
        # and model_fields_set contains the field
        if self.java_script_running_from_omnibox is None and "java_script_running_from_omnibox" in self.model_fields_set:
            _dict['javaScriptRunningFromOmnibox'] = None

        # set to None if pages_with_ssl_errors (nullable) is None
        # and model_fields_set contains the field
        if self.pages_with_ssl_errors is None and "pages_with_ssl_errors" in self.model_fields_set:
            _dict['pagesWithSslErrors'] = None

        # set to None if basic_authentication_over_http (nullable) is None
        # and model_fields_set contains the field
        if self.basic_authentication_over_http is None and "basic_authentication_over_http" in self.model_fields_set:
            _dict['basicAuthenticationOverHttp'] = None

        # set to None if third_party_cookies (nullable) is None
        # and model_fields_set contains the field
        if self.third_party_cookies is None and "third_party_cookies" in self.model_fields_set:
            _dict['thirdPartyCookies'] = None

        # set to None if print_preview (nullable) is None
        # and model_fields_set contains the field
        if self.print_preview is None and "print_preview" in self.model_fields_set:
            _dict['printPreview'] = None

        # set to None if google_cloud_print (nullable) is None
        # and model_fields_set contains the field
        if self.google_cloud_print is None and "google_cloud_print" in self.model_fields_set:
            _dict['googleCloudPrint'] = None

        # set to None if allowed_printers (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_printers is None and "allowed_printers" in self.model_fields_set:
            _dict['allowedPrinters'] = None

        # set to None if open_links_in_external_apps (nullable) is None
        # and model_fields_set contains the field
        if self.open_links_in_external_apps is None and "open_links_in_external_apps" in self.model_fields_set:
            _dict['openLinksInExternalApps'] = None

        # set to None if trusted_certificate_authorities (nullable) is None
        # and model_fields_set contains the field
        if self.trusted_certificate_authorities is None and "trusted_certificate_authorities" in self.model_fields_set:
            _dict['trustedCertificateAuthorities'] = None

        # set to None if remote_host_firewall_traversal (nullable) is None
        # and model_fields_set contains the field
        if self.remote_host_firewall_traversal is None and "remote_host_firewall_traversal" in self.model_fields_set:
            _dict['remoteHostFirewallTraversal'] = None

        # set to None if end_process_via_task_manager (nullable) is None
        # and model_fields_set contains the field
        if self.end_process_via_task_manager is None and "end_process_via_task_manager" in self.model_fields_set:
            _dict['endProcessViaTaskManager'] = None

        # set to None if pdfium (nullable) is None
        # and model_fields_set contains the field
        if self.pdfium is None and "pdfium" in self.model_fields_set:
            _dict['pdfium'] = None

        # set to None if web_gl_api (nullable) is None
        # and model_fields_set contains the field
        if self.web_gl_api is None and "web_gl_api" in self.model_fields_set:
            _dict['webGlApi'] = None

        # set to None if file_system_api (nullable) is None
        # and model_fields_set contains the field
        if self.file_system_api is None and "file_system_api" in self.model_fields_set:
            _dict['fileSystemApi'] = None

        # set to None if sensors_api (nullable) is None
        # and model_fields_set contains the field
        if self.sensors_api is None and "sensors_api" in self.model_fields_set:
            _dict['sensorsApi'] = None

        # set to None if web_serial_api (nullable) is None
        # and model_fields_set contains the field
        if self.web_serial_api is None and "web_serial_api" in self.model_fields_set:
            _dict['webSerialApi'] = None

        # set to None if web_bluetooth_api (nullable) is None
        # and model_fields_set contains the field
        if self.web_bluetooth_api is None and "web_bluetooth_api" in self.model_fields_set:
            _dict['webBluetoothApi'] = None

        # set to None if web_usb_api (nullable) is None
        # and model_fields_set contains the field
        if self.web_usb_api is None and "web_usb_api" in self.model_fields_set:
            _dict['webUsbApi'] = None

        # set to None if web_hid_api (nullable) is None
        # and model_fields_set contains the field
        if self.web_hid_api is None and "web_hid_api" in self.model_fields_set:
            _dict['webHidApi'] = None

        # set to None if quic_protocol (nullable) is None
        # and model_fields_set contains the field
        if self.quic_protocol is None and "quic_protocol" in self.model_fields_set:
            _dict['quicProtocol'] = None

        # set to None if web_clipboard_api (nullable) is None
        # and model_fields_set contains the field
        if self.web_clipboard_api is None and "web_clipboard_api" in self.model_fields_set:
            _dict['webClipboardApi'] = None

        # set to None if local_fonts (nullable) is None
        # and model_fields_set contains the field
        if self.local_fonts is None and "local_fonts" in self.model_fields_set:
            _dict['localFonts'] = None

        # set to None if flush_browser_data (nullable) is None
        # and model_fields_set contains the field
        if self.flush_browser_data is None and "flush_browser_data" in self.model_fields_set:
            _dict['flushBrowserData'] = None

        # set to None if legacy_password_manager (nullable) is None
        # and model_fields_set contains the field
        if self.legacy_password_manager is None and "legacy_password_manager" in self.model_fields_set:
            _dict['legacyPasswordManager'] = None

        # set to None if hide_sensitive_data_from_extensions (nullable) is None
        # and model_fields_set contains the field
        if self.hide_sensitive_data_from_extensions is None and "hide_sensitive_data_from_extensions" in self.model_fields_set:
            _dict['hideSensitiveDataFromExtensions'] = None

        # set to None if internet_explorer_compatibility_mode (nullable) is None
        # and model_fields_set contains the field
        if self.internet_explorer_compatibility_mode is None and "internet_explorer_compatibility_mode" in self.model_fields_set:
            _dict['internetExplorerCompatibilityMode'] = None

        # set to None if launching_external_applications (nullable) is None
        # and model_fields_set contains the field
        if self.launching_external_applications is None and "launching_external_applications" in self.model_fields_set:
            _dict['launchingExternalApplications'] = None

        # set to None if cookies (nullable) is None
        # and model_fields_set contains the field
        if self.cookies is None and "cookies" in self.model_fields_set:
            _dict['cookies'] = None

        # set to None if local_network_access_restrictions (nullable) is None
        # and model_fields_set contains the field
        if self.local_network_access_restrictions is None and "local_network_access_restrictions" in self.model_fields_set:
            _dict['localNetworkAccessRestrictions'] = None

        # set to None if enhanced_tracking_protection (nullable) is None
        # and model_fields_set contains the field
        if self.enhanced_tracking_protection is None and "enhanced_tracking_protection" in self.model_fields_set:
            _dict['enhancedTrackingProtection'] = None

        # set to None if force_https (nullable) is None
        # and model_fields_set contains the field
        if self.force_https is None and "force_https" in self.model_fields_set:
            _dict['forceHttps'] = None

        # set to None if java_script_v8_jit_and_web_assembly (nullable) is None
        # and model_fields_set contains the field
        if self.java_script_v8_jit_and_web_assembly is None and "java_script_v8_jit_and_web_assembly" in self.model_fields_set:
            _dict['javaScriptV8JitAndWebAssembly'] = None

        # set to None if restrict_extension_host_permissions (nullable) is None
        # and model_fields_set contains the field
        if self.restrict_extension_host_permissions is None and "restrict_extension_host_permissions" in self.model_fields_set:
            _dict['restrictExtensionHostPermissions'] = None

        # set to None if web_rtc (nullable) is None
        # and model_fields_set contains the field
        if self.web_rtc is None and "web_rtc" in self.model_fields_set:
            _dict['webRtc'] = None

        # set to None if notifications (nullable) is None
        # and model_fields_set contains the field
        if self.notifications is None and "notifications" in self.model_fields_set:
            _dict['notifications'] = None

        # set to None if popups (nullable) is None
        # and model_fields_set contains the field
        if self.popups is None and "popups" in self.model_fields_set:
            _dict['popups'] = None

        # set to None if pages_with_insecure_content (nullable) is None
        # and model_fields_set contains the field
        if self.pages_with_insecure_content is None and "pages_with_insecure_content" in self.model_fields_set:
            _dict['pagesWithInsecureContent'] = None

        # set to None if kerberos_delegation_allowlist (nullable) is None
        # and model_fields_set contains the field
        if self.kerberos_delegation_allowlist is None and "kerberos_delegation_allowlist" in self.model_fields_set:
            _dict['kerberosDelegationAllowlist'] = None

        # set to None if authentication_server_allowlist (nullable) is None
        # and model_fields_set contains the field
        if self.authentication_server_allowlist is None and "authentication_server_allowlist" in self.model_fields_set:
            _dict['authenticationServerAllowlist'] = None

        # set to None if concurrent_number_of_devices (nullable) is None
        # and model_fields_set contains the field
        if self.concurrent_number_of_devices is None and "concurrent_number_of_devices" in self.model_fields_set:
            _dict['concurrentNumberOfDevices'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecurityControls from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "developerToolsForExtensions": AllowBlockControl.from_dict(obj["developerToolsForExtensions"]) if obj.get("developerToolsForExtensions") is not None else None,
            "cast": AllowBlockControl.from_dict(obj["cast"]) if obj.get("cast") is not None else None,
            "cookiesProtection": EnableDisableControl.from_dict(obj["cookiesProtection"]) if obj.get("cookiesProtection") is not None else None,
            "browserHistory": BrowserHistoryControl.from_dict(obj["browserHistory"]) if obj.get("browserHistory") is not None else None,
            "dnsOverHttps": DnsOverHttpsControl.from_dict(obj["dnsOverHttps"]) if obj.get("dnsOverHttps") is not None else None,
            "browserSelfProtection": BrowserSelfProtectionControl.from_dict(obj["browserSelfProtection"]) if obj.get("browserSelfProtection") is not None else None,
            "keyloggingProtection": KeyloggingProtectionControl.from_dict(obj["keyloggingProtection"]) if obj.get("keyloggingProtection") is not None else None,
            "browserLock": BrowserLockControl.from_dict(obj["browserLock"]) if obj.get("browserLock") is not None else None,
            "authenticationFactor": AuthenticationFactorControl.from_dict(obj["authenticationFactor"]) if obj.get("authenticationFactor") is not None else None,
            "sessionRefresh": SessionRefreshControl.from_dict(obj["sessionRefresh"]) if obj.get("sessionRefresh") is not None else None,
            "nativeMessagingHosts": NativeMessagingHostsControl.from_dict(obj["nativeMessagingHosts"]) if obj.get("nativeMessagingHosts") is not None else None,
            "allowedOrBlockedExtensions": AllowedOrBlockedExtensionsControl.from_dict(obj["allowedOrBlockedExtensions"]) if obj.get("allowedOrBlockedExtensions") is not None else None,
            "blockExtensionsByPermissions": BlockExtensionsByPermissionsControl.from_dict(obj["blockExtensionsByPermissions"]) if obj.get("blockExtensionsByPermissions") is not None else None,
            "postQuantumKeySecurity": PostQuantumKeySecurityControl.from_dict(obj["postQuantumKeySecurity"]) if obj.get("postQuantumKeySecurity") is not None else None,
            "strictOriginIsolation": EnableDisableControl.from_dict(obj["strictOriginIsolation"]) if obj.get("strictOriginIsolation") is not None else None,
            "advancedBrowserProtection": EnableDisableControl.from_dict(obj["advancedBrowserProtection"]) if obj.get("advancedBrowserProtection") is not None else None,
            "userDataDirectoryProtection": EnableDisableControl.from_dict(obj["userDataDirectoryProtection"]) if obj.get("userDataDirectoryProtection") is not None else None,
            "mobilePasswordSaving": AllowBlockControl.from_dict(obj["mobilePasswordSaving"]) if obj.get("mobilePasswordSaving") is not None else None,
            "autofillOfForms": AllowBlockControl.from_dict(obj["autofillOfForms"]) if obj.get("autofillOfForms") is not None else None,
            "autofillOfCreditCards": AllowBlockControl.from_dict(obj["autofillOfCreditCards"]) if obj.get("autofillOfCreditCards") is not None else None,
            "javaScriptRunningFromOmnibox": AllowBlockControl.from_dict(obj["javaScriptRunningFromOmnibox"]) if obj.get("javaScriptRunningFromOmnibox") is not None else None,
            "pagesWithSslErrors": AllowBlockControl.from_dict(obj["pagesWithSslErrors"]) if obj.get("pagesWithSslErrors") is not None else None,
            "basicAuthenticationOverHttp": AllowBlockControl.from_dict(obj["basicAuthenticationOverHttp"]) if obj.get("basicAuthenticationOverHttp") is not None else None,
            "thirdPartyCookies": AllowBlockControl.from_dict(obj["thirdPartyCookies"]) if obj.get("thirdPartyCookies") is not None else None,
            "printPreview": AllowBlockControl.from_dict(obj["printPreview"]) if obj.get("printPreview") is not None else None,
            "googleCloudPrint": AllowBlockControl.from_dict(obj["googleCloudPrint"]) if obj.get("googleCloudPrint") is not None else None,
            "allowedPrinters": AllowedPrintersControl.from_dict(obj["allowedPrinters"]) if obj.get("allowedPrinters") is not None else None,
            "openLinksInExternalApps": OpenLinksInExternalAppsControl.from_dict(obj["openLinksInExternalApps"]) if obj.get("openLinksInExternalApps") is not None else None,
            "trustedCertificateAuthorities": TrustedCertificateAuthoritiesControl.from_dict(obj["trustedCertificateAuthorities"]) if obj.get("trustedCertificateAuthorities") is not None else None,
            "remoteHostFirewallTraversal": AllowBlockControl.from_dict(obj["remoteHostFirewallTraversal"]) if obj.get("remoteHostFirewallTraversal") is not None else None,
            "endProcessViaTaskManager": AllowBlockControl.from_dict(obj["endProcessViaTaskManager"]) if obj.get("endProcessViaTaskManager") is not None else None,
            "pdfium": AllowBlockControl.from_dict(obj["pdfium"]) if obj.get("pdfium") is not None else None,
            "webGlApi": AllowBlockControl.from_dict(obj["webGlApi"]) if obj.get("webGlApi") is not None else None,
            "fileSystemApi": AllowBlockControl.from_dict(obj["fileSystemApi"]) if obj.get("fileSystemApi") is not None else None,
            "sensorsApi": AllowBlockControl.from_dict(obj["sensorsApi"]) if obj.get("sensorsApi") is not None else None,
            "webSerialApi": AllowBlockControl.from_dict(obj["webSerialApi"]) if obj.get("webSerialApi") is not None else None,
            "webBluetoothApi": AllowBlockControl.from_dict(obj["webBluetoothApi"]) if obj.get("webBluetoothApi") is not None else None,
            "webUsbApi": AllowBlockControl.from_dict(obj["webUsbApi"]) if obj.get("webUsbApi") is not None else None,
            "webHidApi": AllowBlockControl.from_dict(obj["webHidApi"]) if obj.get("webHidApi") is not None else None,
            "quicProtocol": AllowBlockControl.from_dict(obj["quicProtocol"]) if obj.get("quicProtocol") is not None else None,
            "webClipboardApi": AllowBlockControl.from_dict(obj["webClipboardApi"]) if obj.get("webClipboardApi") is not None else None,
            "localFonts": AllowBlockControl.from_dict(obj["localFonts"]) if obj.get("localFonts") is not None else None,
            "flushBrowserData": FlushBrowserDataControl.from_dict(obj["flushBrowserData"]) if obj.get("flushBrowserData") is not None else None,
            "legacyPasswordManager": LegacyPasswordManagerControl.from_dict(obj["legacyPasswordManager"]) if obj.get("legacyPasswordManager") is not None else None,
            "hideSensitiveDataFromExtensions": EnableDisableControl.from_dict(obj["hideSensitiveDataFromExtensions"]) if obj.get("hideSensitiveDataFromExtensions") is not None else None,
            "internetExplorerCompatibilityMode": InternetExplorerCompatibilityModeControl.from_dict(obj["internetExplorerCompatibilityMode"]) if obj.get("internetExplorerCompatibilityMode") is not None else None,
            "launchingExternalApplications": LaunchingExternalApplicationsControl.from_dict(obj["launchingExternalApplications"]) if obj.get("launchingExternalApplications") is not None else None,
            "cookies": CookiesControl.from_dict(obj["cookies"]) if obj.get("cookies") is not None else None,
            "localNetworkAccessRestrictions": LocalNetworkAccessRestrictionsControl.from_dict(obj["localNetworkAccessRestrictions"]) if obj.get("localNetworkAccessRestrictions") is not None else None,
            "enhancedTrackingProtection": EnhancedTrackingProtectionControl.from_dict(obj["enhancedTrackingProtection"]) if obj.get("enhancedTrackingProtection") is not None else None,
            "forceHttps": ForceHttpsControl.from_dict(obj["forceHttps"]) if obj.get("forceHttps") is not None else None,
            "javaScriptV8JitAndWebAssembly": JavaScriptV8JitAndWebAssemblyControl.from_dict(obj["javaScriptV8JitAndWebAssembly"]) if obj.get("javaScriptV8JitAndWebAssembly") is not None else None,
            "restrictExtensionHostPermissions": RestrictExtensionHostPermissionsControl.from_dict(obj["restrictExtensionHostPermissions"]) if obj.get("restrictExtensionHostPermissions") is not None else None,
            "webRtc": WebRtcControl.from_dict(obj["webRtc"]) if obj.get("webRtc") is not None else None,
            "notifications": NotificationsControl.from_dict(obj["notifications"]) if obj.get("notifications") is not None else None,
            "popups": PopupsControl.from_dict(obj["popups"]) if obj.get("popups") is not None else None,
            "pagesWithInsecureContent": PagesWithInsecureContentControl.from_dict(obj["pagesWithInsecureContent"]) if obj.get("pagesWithInsecureContent") is not None else None,
            "kerberosDelegationAllowlist": KerberosDelegationAllowlistControl.from_dict(obj["kerberosDelegationAllowlist"]) if obj.get("kerberosDelegationAllowlist") is not None else None,
            "authenticationServerAllowlist": AuthenticationServerAllowlistControl.from_dict(obj["authenticationServerAllowlist"]) if obj.get("authenticationServerAllowlist") is not None else None,
            "concurrentNumberOfDevices": ConcurrentNumberOfDevicesControl.from_dict(obj["concurrentNumberOfDevices"]) if obj.get("concurrentNumberOfDevices") is not None else None
        })
        return _obj


